INSERT INTO school (id, school_name) VALUES ( 1, 'KV (3 BRD) No.2 CHANDIGARH');
INSERT INTO school (id, school_name) VALUES ( 2, 'KV (9 BRD) No.3 PUNE');
INSERT INTO school (id, school_name) VALUES ( 3, 'KV (AFA) No.1 DUNDIGAL');
INSERT INTO school (id, school_name) VALUES ( 4, 'KV (AFS) AMLA');
INSERT INTO school (id, school_name) VALUES ( 5, 'KV (AFS) ARJANGARH');
INSERT INTO school (id, school_name) VALUES ( 6, 'KV (AFS) AVADI');
INSERT INTO school (id, school_name) VALUES ( 7, 'KV (AFS) AWANTIPURA');
INSERT INTO school (id, school_name) VALUES ( 8, 'KV (AFS) BAKSHI KA TALAB');
INSERT INTO school (id, school_name) VALUES ( 9, 'KV (AFS) BAMRAULI');
INSERT INTO school (id, school_name) VALUES ( 10, 'KV (AFS) BAREILLY');
INSERT INTO school (id, school_name) VALUES ( 11, 'KV (AFS) BARNALA');
INSERT INTO school (id, school_name) VALUES ( 12, 'KV (AFS) BARRACKPORE');
INSERT INTO school (id, school_name) VALUES ( 13, 'KV (AFS) BAWANA');
INSERT INTO school (id, school_name) VALUES ( 14, 'KV (AFS) BEGUMPET');
INSERT INTO school (id, school_name) VALUES ( 15, 'KV (AFS) BidAR');
INSERT INTO school (id, school_name) VALUES ( 16, 'KV (AFS) BIHATA');
INSERT INTO school (id, school_name) VALUES ( 17, 'KV (AFS) CHANDI NAGAR');
INSERT INTO school (id, school_name) VALUES ( 18, 'KV (AFS) DARJEEPURA');
INSERT INTO school (id, school_name) VALUES ( 19, 'KV (AFS) DIGARU');
INSERT INTO school (id, school_name) VALUES ( 20, 'KV (AFS) HAKIMPET SECUNDERABAD');
INSERT INTO school (id, school_name) VALUES ( 21, 'KV (AFS) JAISALMER');
INSERT INTO school (id, school_name) VALUES ( 22, 'KV (AFS) KASAULI');
INSERT INTO school (id, school_name) VALUES ( 23, 'KV (AFS) KUMBHIRGRAM');
INSERT INTO school (id, school_name) VALUES ( 24, 'KV (AFS) LAITKOR PEAK SHILLONG');
INSERT INTO school (id, school_name) VALUES ( 25, 'KV (AFS) MEMAURA');
INSERT INTO school (id, school_name) VALUES ( 26, 'KV (AFS) NALIYA');
INSERT INTO school (id, school_name) VALUES ( 27, 'KV (AFS) No.1 AGRA CANTT');
INSERT INTO school (id, school_name) VALUES ( 28, 'KV (AFS) No.1 BHUJ');
INSERT INTO school (id, school_name) VALUES ( 29, 'KV (AFS) No.1 DARBHANGA');
INSERT INTO school (id, school_name) VALUES ( 30, 'KV (AFS) No.1 GURGAON');
INSERT INTO school (id, school_name) VALUES ( 31, 'KV (AFS) No.1 HALWARA');
INSERT INTO school (id, school_name) VALUES ( 32, 'KV (AFS) No.1 JALAHALLI');
INSERT INTO school (id, school_name) VALUES ( 33, 'KV (AFS) No.1 JODHPUR');
INSERT INTO school (id, school_name) VALUES ( 34, 'KV (AFS) No.1 JORHAT');
INSERT INTO school (id, school_name) VALUES ( 35, 'KV (AFS) No.1 PATHANKOT');
INSERT INTO school (id, school_name) VALUES ( 36, 'KV (AFS) No.1 PUNE');
INSERT INTO school (id, school_name) VALUES ( 37, 'KV (AFS) No.1 SIRSA');
INSERT INTO school (id, school_name) VALUES ( 38, 'KV (AFS) No.1 SURATGARH');
INSERT INTO school (id, school_name) VALUES ( 39, 'KV (AFS) No.1 TAMBARAM');
INSERT INTO school (id, school_name) VALUES ( 40, 'KV (AFS) No.2 DEVLALI');
INSERT INTO school (id, school_name) VALUES ( 41, 'KV (AFS) No.2 GWALIOR');
INSERT INTO school (id, school_name) VALUES ( 42, 'KV (AFS) No.2 HALWARA');
INSERT INTO school (id, school_name) VALUES ( 43, 'KV (AFS) No.2 JALAHALLI');
INSERT INTO school (id, school_name) VALUES ( 44, 'KV (AFS) No.2 JODHPUR');
INSERT INTO school (id, school_name) VALUES ( 45, 'KV (AFS) No.2 PUNE');
INSERT INTO school (id, school_name) VALUES ( 46, 'KV (AFS) No.2 SRINAGAR');
INSERT INTO school (id, school_name) VALUES ( 47, 'KV (AFS) No.2 SURATGARH');
INSERT INTO school (id, school_name) VALUES ( 48, 'KV (AFS) No.2 TEZPUR');
INSERT INTO school (id, school_name) VALUES ( 49, 'KV (AFS) No.3 BHATINDA');
INSERT INTO school (id, school_name) VALUES ( 50, 'KV (AFS) No.3 NAL BIKANER');
INSERT INTO school (id, school_name) VALUES ( 51, 'KV (AFS) OJHAR');
INSERT INTO school (id, school_name) VALUES ( 52, 'KV (AFS) RAJOKARI');
INSERT INTO school (id, school_name) VALUES ( 53, 'KV (AFS) SALUA');
INSERT INTO school (id, school_name) VALUES ( 54, 'KV (AFS) SAMANA');
INSERT INTO school (id, school_name) VALUES ( 55, 'KV (AFS) SAMBRA');
INSERT INTO school (id, school_name) VALUES ( 56, 'KV (AFS) SARSAWA');
INSERT INTO school (id, school_name) VALUES ( 57, 'KV (AFS) SINGHARSHI');
INSERT INTO school (id, school_name) VALUES ( 58, 'KV (AFS) SURYA LANKA');
INSERT INTO school (id, school_name) VALUES ( 59, 'KV (AFS) THANE');
INSERT INTO school (id, school_name) VALUES ( 60, 'KV (AFS) THANJAVUR');
INSERT INTO school (id, school_name) VALUES ( 61, 'KV (AFS) TRIVENDRAM AKKULAM');
INSERT INTO school (id, school_name) VALUES ( 62, 'KV (AFS) TUGHLAKABAD');
INSERT INTO school (id, school_name) VALUES ( 63, 'KV (AFS) WADSAR');
INSERT INTO school (id, school_name) VALUES ( 64, 'KV (AFS) YELAHANKA');
INSERT INTO school (id, school_name) VALUES ( 65, 'KV (AGPP) ANTA');
INSERT INTO school (id, school_name) VALUES ( 66, 'KV (AMC) LUCKNOW');
INSERT INTO school (id, school_name) VALUES ( 67, 'KV (AOC) JABALPUR');
INSERT INTO school (id, school_name) VALUES ( 68, 'KV (ARC) DOOM DOOMA');
INSERT INTO school (id, school_name) VALUES ( 69, 'KV (ARMY) BARRACKPORE');
INSERT INTO school (id, school_name) VALUES ( 70, 'KV (ARMY) No.2 JODHPUR');
INSERT INTO school (id, school_name) VALUES ( 71, 'KV (ASC)BAREILLY');
INSERT INTO school (id, school_name) VALUES ( 72, 'KV (BHEL) JAGDISHPUR');
INSERT INTO school (id, school_name) VALUES ( 73, 'KV (BHU) VARANASI');
INSERT INTO school (id, school_name) VALUES ( 74, 'KV (BIOP) BACHELI');
INSERT INTO school (id, school_name) VALUES ( 75, 'KV (BIOP) KIRANDUL');
INSERT INTO school (id, school_name) VALUES ( 76, 'KV (BSF) AMARKOT');
INSERT INTO school (id, school_name) VALUES ( 77, 'KV (BSF) ANOOPGARH');
INSERT INTO school (id, school_name) VALUES ( 78, 'KV (BSF) ARADHPUR');
INSERT INTO school (id, school_name) VALUES ( 79, 'KV (BSF) BAGAFA');
INSERT INTO school (id, school_name) VALUES ( 80, 'KV (BSF) BAIKUNTHPUR');
INSERT INTO school (id, school_name) VALUES ( 81, 'KV (BSF) BANDIPUR');
INSERT INTO school (id, school_name) VALUES ( 82, 'KV (BSF) BHIKIWIND');
INSERT INTO school (id, school_name) VALUES ( 83, 'KV (BSF) CHAKUR');
INSERT INTO school (id, school_name) VALUES ( 84, 'KV (BSF) CHHAWALA CAMP');
INSERT INTO school (id, school_name) VALUES ( 85, 'KV (BSF) CHURA CHAND PUR');
INSERT INTO school (id, school_name) VALUES ( 86, 'KV (BSF) DABLA');
INSERT INTO school (id, school_name) VALUES ( 87, 'KV (BSF) DANTIWADA');
INSERT INTO school (id, school_name) VALUES ( 88, 'KV (BSF) DHOLCHERA');
INSERT INTO school (id, school_name) VALUES ( 89, 'KV (BSF) FAZILKA');
INSERT INTO school (id, school_name) VALUES ( 90, 'KV (BSF) GANDHINAGAR');
INSERT INTO school (id, school_name) VALUES ( 91, 'KV (BSF) HAZARIBAGH');
INSERT INTO school (id, school_name) VALUES ( 92, 'KV (BSF) HUMHAMA');
INSERT INTO school (id, school_name) VALUES ( 93, 'KV (BSF) JALALABAD');
INSERT INTO school (id, school_name) VALUES ( 94, 'KV (BSF) JODHPUR');
INSERT INTO school (id, school_name) VALUES ( 95, 'KV (BSF) KHAJUWALA');
INSERT INTO school (id, school_name) VALUES ( 96, 'KV (BSF) KISHAN GANJ');
INSERT INTO school (id, school_name) VALUES ( 97, 'KV (BSF) KMS WALA');
INSERT INTO school (id, school_name) VALUES ( 98, 'KV (BSF) KRISHNA NAGAR');
INSERT INTO school (id, school_name) VALUES ( 99, 'KV (BSF) No.2 INDORE');
INSERT INTO school (id, school_name) VALUES ( 100, 'KV (BSF) No.3 PANTHACHOWK SRINAGAR');
INSERT INTO school (id, school_name) VALUES ( 101, 'KV (BSF) PANBARI');
INSERT INTO school (id, school_name) VALUES ( 102, 'KV (BSF) PANISAGAR');
INSERT INTO school (id, school_name) VALUES ( 103, 'KV (BSF) POKHRAN');
INSERT INTO school (id, school_name) VALUES ( 104, 'KV (BSF) RAISINGHNAGAR');
INSERT INTO school (id, school_name) VALUES ( 105, 'KV (BSF) RAJOURI');
INSERT INTO school (id, school_name) VALUES ( 106, 'KV (BSF) RAMGARH');
INSERT INTO school (id, school_name) VALUES ( 107, 'KV (BSF) RANINAGAR');
INSERT INTO school (id, school_name) VALUES ( 108, 'KV (BSF) SHIKAR PUR');
INSERT INTO school (id, school_name) VALUES ( 109, 'KV (BSF) SUNDERBANI');
INSERT INTO school (id, school_name) VALUES ( 110, 'KV (BSF) TALIAMURA. KHASIAMANGAL');
INSERT INTO school (id, school_name) VALUES ( 111, 'KV (CCI) BOKAJAN');
INSERT INTO school (id, school_name) VALUES ( 112, 'KV (CCL) RANCHI');
INSERT INTO school (id, school_name) VALUES ( 113, 'KV (CISF) BARWAHA');
INSERT INTO school (id, school_name) VALUES ( 114, 'KV (CISF) BHILAI');
INSERT INTO school (id, school_name) VALUES ( 115, 'KV (CISF) DEOLI');
INSERT INTO school (id, school_name) VALUES ( 116, 'KV (CISF) JAIPUR');
INSERT INTO school (id, school_name) VALUES ( 117, 'KV (CISF) No.2 ARAKKONAM');
INSERT INTO school (id, school_name) VALUES ( 118, 'KV (CLW) CHITTARANJAN');
INSERT INTO school (id, school_name) VALUES ( 119, 'KV (CMERI) DURGAPUR');
INSERT INTO school (id, school_name) VALUES ( 120, 'KV (COD) JABALPUR');
INSERT INTO school (id, school_name) VALUES ( 121, 'KV (CRPF) ALLAHABAD');
INSERT INTO school (id, school_name) VALUES ( 122, 'KV (CRPF) AMERIGOG');
INSERT INTO school (id, school_name) VALUES ( 123, 'KV (CRPF) AVADI');
INSERT INTO school (id, school_name) VALUES ( 124, 'KV (CRPF) BANGRASIA');
INSERT INTO school (id, school_name) VALUES ( 125, 'KV (CRPF) BANTALAB');
INSERT INTO school (id, school_name) VALUES ( 126, 'KV (CRPF) BIJNOUR');
INSERT INTO school (id, school_name) VALUES ( 127, 'KV (CRPF) BILASPUR');
INSERT INTO school (id, school_name) VALUES ( 128, 'KV (CRPF) DIMAPUR');
INSERT INTO school (id, school_name) VALUES ( 129, 'KV (CRPF) DURGAPUR');
INSERT INTO school (id, school_name) VALUES ( 130, 'KV (CRPF) GANDHINAGAR');
INSERT INTO school (id, school_name) VALUES ( 131, 'KV (CRPF) GC BARKAS');
INSERT INTO school (id, school_name) VALUES ( 132, 'KV (CRPF) JHAPHAN');
INSERT INTO school (id, school_name) VALUES ( 133, 'KV (CRPF) JHARODA KALAN');
INSERT INTO school (id, school_name) VALUES ( 134, 'KV (CRPF) KADARPUR');
INSERT INTO school (id, school_name) VALUES ( 135, 'KV (CRPF) KHATI');
INSERT INTO school (id, school_name) VALUES ( 136, 'KV (CRPF) LARIE HILL KOHIMA');
INSERT INTO school (id, school_name) VALUES ( 137, 'KV (CRPF) MOKAM GHAT');
INSERT INTO school (id, school_name) VALUES ( 138, 'KV (CRPF) MOUNTABU');
INSERT INTO school (id, school_name) VALUES ( 139, 'KV (CRPF) MUDKHED');
INSERT INTO school (id, school_name) VALUES ( 140, 'KV (CRPF) NAGPUR');
INSERT INTO school (id, school_name) VALUES ( 141, 'KV (CRPF) NEEMUCH');
INSERT INTO school (id, school_name) VALUES ( 142, 'KV (CRPF) No.1 AJMER');
INSERT INTO school (id, school_name) VALUES ( 143, 'KV (CRPF) No.2 AJMER');
INSERT INTO school (id, school_name) VALUES ( 144, 'KV (CRPF) No.2 BHUBANESHWAR');
INSERT INTO school (id, school_name) VALUES ( 145, 'KV (CRPF) No.2 IMPHAL');
INSERT INTO school (id, school_name) VALUES ( 146, 'KV (CRPF) PALLIPURAM');
INSERT INTO school (id, school_name) VALUES ( 147, 'KV (CRPF) PERINGOME');
INSERT INTO school (id, school_name) VALUES ( 148, 'KV (CRPF) PINJORE');
INSERT INTO school (id, school_name) VALUES ( 149, 'KV (CRPF) RAMPUR');
INSERT INTO school (id, school_name) VALUES ( 150, 'KV (CRPF) RANCHI');
INSERT INTO school (id, school_name) VALUES ( 151, 'KV (CRPF) SARAIKHAS');
INSERT INTO school (id, school_name) VALUES ( 152, 'KV (CRPF) TELIGAON');
INSERT INTO school (id, school_name) VALUES ( 153, 'KV (CRPF) YELAHANKA');
INSERT INTO school (id, school_name) VALUES ( 154, 'KV (CTBS) CHANDRAPURA');
INSERT INTO school (id, school_name) VALUES ( 155, 'KV (DLW) VARANASI');
INSERT INTO school (id, school_name) VALUES ( 156, 'KV (DRDO) KANCHAN BAGH');
INSERT INTO school (id, school_name) VALUES ( 157, 'KV (DVC) MAITHAN DAM');
INSERT INTO school (id, school_name) VALUES ( 158, 'KV (HAPPY VALLEY)SHILLONG');
INSERT INTO school (id, school_name) VALUES ( 159, 'KV (HEC) RANCHI');
INSERT INTO school (id, school_name) VALUES ( 160, 'KV (HPC) CACHAR PANCHGRAM');
INSERT INTO school (id, school_name) VALUES ( 161, 'KV (HPC) JAGIROAD');
INSERT INTO school (id, school_name) VALUES ( 162, 'KV (IFFCO) AONLA BAREILLY');
INSERT INTO school (id, school_name) VALUES ( 163, 'KV (IFFCO) PHULPUR');
INSERT INTO school (id, school_name) VALUES ( 164, 'KV (IIT) KANPUR');
INSERT INTO school (id, school_name) VALUES ( 165, 'KV (IIT) No.1 KHARAGPUR');
INSERT INTO school (id, school_name) VALUES ( 166, 'KV (INS) MANDOVI');
INSERT INTO school (id, school_name) VALUES ( 167, 'KV (IOC) HALDIA');
INSERT INTO school (id, school_name) VALUES ( 168, 'KV (IOC) No.2 BARAUNI');
INSERT INTO school (id, school_name) VALUES ( 169, 'KV (IOP) MEGHAHATUBURU');
INSERT INTO school (id, school_name) VALUES ( 170, 'KV (ISP) No.2 NASIK ROAD CAMP');
INSERT INTO school (id, school_name) VALUES ( 171, 'KV (ITI) MANKAPUR');
INSERT INTO school (id, school_name) VALUES ( 172, 'KV (IVRI) IZZAT NAGAR BAREILLY');
INSERT INTO school (id, school_name) VALUES ( 173, 'KV (IVRI) MUKTESHWAR');
INSERT INTO school (id, school_name) VALUES ( 174, 'KV (JRC) BAREILLY');
INSERT INTO school (id, school_name) VALUES ( 175, 'KV (KUNJBAN) No.1 AGARTALA');
INSERT INTO school (id, school_name) VALUES ( 176, 'KV (LAMPHELPAT) No.1 IMPHAL');
INSERT INTO school (id, school_name) VALUES ( 177, 'KV (LEIMAKHONG) No.3 IMPHAL');
INSERT INTO school (id, school_name) VALUES ( 178, 'KV (MIRC) No.2 AHMEDNAGAR');
INSERT INTO school (id, school_name) VALUES ( 179, 'KV (NAD) ALWAYE');
INSERT INTO school (id, school_name) VALUES ( 180, 'KV (NDA) KHADAK VASLA');
INSERT INTO school (id, school_name) VALUES ( 181, 'KV (NEHU) SHILLONG');
INSERT INTO school (id, school_name) VALUES ( 182, 'KV (NEPA) BARAPANI');
INSERT INTO school (id, school_name) VALUES ( 183, 'KV (NER) IZZAT NAGAR');
INSERT INTO school (id, school_name) VALUES ( 184, 'KV (NHPC) MALDA');
INSERT INTO school (id, school_name) VALUES ( 185, 'KV (NMU) JALGAON');
INSERT INTO school (id, school_name) VALUES ( 186, 'KV (NPA) SVP');
INSERT INTO school (id, school_name) VALUES ( 187, 'KV (NSG) MANESAR');
INSERT INTO school (id, school_name) VALUES ( 188, 'KV (NTPC) DIBYAPUR');
INSERT INTO school (id, school_name) VALUES ( 189, 'KV (NTPC) FARAKKA');
INSERT INTO school (id, school_name) VALUES ( 190, 'KV (NTPC) KAHAL GAON');
INSERT INTO school (id, school_name) VALUES ( 191, 'KV (NTPC) RAMAGUNDAM');
INSERT INTO school (id, school_name) VALUES ( 192, 'KV (NTPC) RIHAND NAGAR');
INSERT INTO school (id, school_name) VALUES ( 193, 'KV (NTPC)(BCPP) No.4 KORBA');
INSERT INTO school (id, school_name) VALUES ( 194, 'KV (OCF) No.2 SHAHJAHANPUR');
INSERT INTO school (id, school_name) VALUES ( 195, 'KV (OIL)DULIAJAN');
INSERT INTO school (id, school_name) VALUES ( 196, 'KV (ONGC) No.2 AGARTALA');
INSERT INTO school (id, school_name) VALUES ( 197, 'KV (ONGC) RAJAHMUNDARY');
INSERT INTO school (id, school_name) VALUES ( 198, 'KV (ONGC) SONAI ROAD');
INSERT INTO school (id, school_name) VALUES ( 199, 'KV (ONGC)PANVEL');
INSERT INTO school (id, school_name) VALUES ( 200, 'KV (RLY) No.2 KATNI');
INSERT INTO school (id, school_name) VALUES ( 201, 'KV (RLY) No.2 KHARAGPUR');
INSERT INTO school (id, school_name) VALUES ( 202, 'KV (RLY) No.3 BOKARO');
INSERT INTO school (id, school_name) VALUES ( 203, 'KV (SANTOKHGARH) SALOH');
INSERT INTO school (id, school_name) VALUES ( 204, 'KV (SC) PUNE');
INSERT INTO school (id, school_name) VALUES ( 205, 'KV (SECL) BAIKUNTPUR');
INSERT INTO school (id, school_name) VALUES ( 206, 'KV (SECL) CHIRI MIRI');
INSERT INTO school (id, school_name) VALUES ( 207, 'KV (SECL) DHANPURI');
INSERT INTO school (id, school_name) VALUES ( 208, 'KV (SECL) JHAGRAKHAND');
INSERT INTO school (id, school_name) VALUES ( 209, 'KV (SECL) No.3 KORBA');
INSERT INTO school (id, school_name) VALUES ( 210, 'KV (SECL) NOWROZABAD');
INSERT INTO school (id, school_name) VALUES ( 211, 'KV (SHEP) JYOTIPURAM');
INSERT INTO school (id, school_name) VALUES ( 212, 'KV (SK UNIVERSITY) ANANTAPUR');
INSERT INTO school (id, school_name) VALUES ( 213, 'KV (SOI) No.1 UPPAL');
INSERT INTO school (id, school_name) VALUES ( 214, 'KV (SSB) HAFLONG');
INSERT INTO school (id, school_name) VALUES ( 215, 'KV (SSB) SRINAGAR');
INSERT INTO school (id, school_name) VALUES ( 216, 'KV (SUKNA) KHAPRAIL');
INSERT INTO school (id, school_name) VALUES ( 217, 'KV (SWRI) AVIKANAGAR');
INSERT INTO school (id, school_name) VALUES ( 218, 'KV (THERMAL) BOKARO');
INSERT INTO school (id, school_name) VALUES ( 219, 'KV (VF) JABALPUR');
INSERT INTO school (id, school_name) VALUES ( 220, 'KV (VRDE) No.3 AHMEDNAGAR');
INSERT INTO school (id, school_name) VALUES ( 221, 'KV (VSN) NAGPUR');
INSERT INTO school (id, school_name) VALUES ( 222, 'KV (WCL) CHANDRAPUR');
INSERT INTO school (id, school_name) VALUES ( 223, 'KV (WCL) NEW MAJARI');
INSERT INTO school (id, school_name) VALUES ( 224, 'KV 210 COBRA CRPF');
INSERT INTO school (id, school_name) VALUES ( 225, 'KV 59 BN SSB NANPARA BAHRAICH');
INSERT INTO school (id, school_name) VALUES ( 226, 'KV AAYER VARANASI');
INSERT INTO school (id, school_name) VALUES ( 227, 'KV ABOHAR');
INSERT INTO school (id, school_name) VALUES ( 228, 'KV ADILABAD');
INSERT INTO school (id, school_name) VALUES ( 229, 'KV ADOOR');
INSERT INTO school (id, school_name) VALUES ( 230, 'KV ADRA');
INSERT INTO school (id, school_name) VALUES ( 231, 'KV AG No.5 GWALIOR');
INSERT INTO school (id, school_name) VALUES ( 232, 'KV AGAR MALWA');
INSERT INTO school (id, school_name) VALUES ( 233, 'KV AGAR MALWA');
INSERT INTO school (id, school_name) VALUES ( 234, 'KV AGCR COLONY');
INSERT INTO school (id, school_name) VALUES ( 235, 'KV AHMEDABAD CANTT');
INSERT INTO school (id, school_name) VALUES ( 236, 'KV AINWAN');
INSERT INTO school (id, school_name) VALUES ( 237, 'KV AIZAWL');
INSERT INTO school (id, school_name) VALUES ( 238, 'KV AJNI');
INSERT INTO school (id, school_name) VALUES ( 239, 'KV AKAMPAT');
INSERT INTO school (id, school_name) VALUES ( 240, 'KV ALHILAL');
INSERT INTO school (id, school_name) VALUES ( 241, 'KV ALIGANJ');
INSERT INTO school (id, school_name) VALUES ( 242, 'KV ALIGARH');
INSERT INTO school (id, school_name) VALUES ( 243, 'KV ALIPORE (COMMAND HOSPITAL)');
INSERT INTO school (id, school_name) VALUES ( 244, 'KV ALIPURDUAR JN.');
INSERT INTO school (id, school_name) VALUES ( 245, 'KV ALIRAJPUR');
INSERT INTO school (id, school_name) VALUES ( 246, 'KV ALMORA');
INSERT INTO school (id, school_name) VALUES ( 247, 'KV ALONG (11 ASSAM RIFLES)');
INSERT INTO school (id, school_name) VALUES ( 248, 'KV ALWAR');
INSERT INTO school (id, school_name) VALUES ( 249, 'KV AMBAH');
INSERT INTO school (id, school_name) VALUES ( 250, 'KV AMBAJHARI');
INSERT INTO school (id, school_name) VALUES ( 251, 'KV AMBARNATH');
INSERT INTO school (id, school_name) VALUES ( 252, 'KV AMBIKA PUR');
INSERT INTO school (id, school_name) VALUES ( 253, 'KV AMHAT. SULTANPUR');
INSERT INTO school (id, school_name) VALUES ( 254, 'KV AMINOO');
INSERT INTO school (id, school_name) VALUES ( 255, 'KV ANANDAPUR');
INSERT INTO school (id, school_name) VALUES ( 256, 'KV ANANTNAG');
INSERT INTO school (id, school_name) VALUES ( 257, 'KV ANDAL');
INSERT INTO school (id, school_name) VALUES ( 258, 'KV ANDREWS GANJ');
INSERT INTO school (id, school_name) VALUES ( 259, 'KV ANGUL');
INSERT INTO school (id, school_name) VALUES ( 260, 'KV ANNA NAGAR CHENNAI');
INSERT INTO school (id, school_name) VALUES ( 261, 'KV ANUPPUR');
INSERT INTO school (id, school_name) VALUES ( 262, 'KV ARAH');
INSERT INTO school (id, school_name) VALUES ( 263, 'KV ARARIA');
INSERT INTO school (id, school_name) VALUES ( 264, 'KV ARC CHARBATIA');
INSERT INTO school (id, school_name) VALUES ( 265, 'KV ARMY AREA PUNE');
INSERT INTO school (id, school_name) VALUES ( 266, 'KV Army No.1 JODHPUR');
INSERT INTO school (id, school_name) VALUES ( 267, 'KV ARUVANKADU');
INSERT INTO school (id, school_name) VALUES ( 268, 'KV ASANSOL');
INSERT INTO school (id, school_name) VALUES ( 269, 'KV ASC BANGALORE');
INSERT INTO school (id, school_name) VALUES ( 270, 'KV ASKA');
INSERT INTO school (id, school_name) VALUES ( 271, 'KV ASSAM UNIVERSITY');
INSERT INTO school (id, school_name) VALUES ( 272, 'KV AUGUSTYAMUNI');
INSERT INTO school (id, school_name) VALUES ( 273, 'KV AURANGABAD');
INSERT INTO school (id, school_name) VALUES ( 274, 'KV AURANGABAD CANTT');
INSERT INTO school (id, school_name) VALUES ( 275, 'KV AZAMGARH');
INSERT INTO school (id, school_name) VALUES ( 276, 'KV B.S.F. ACADEMY TEKANPUR');
INSERT INTO school (id, school_name) VALUES ( 277, 'KV BABINA CANTT');
INSERT INTO school (id, school_name) VALUES ( 278, 'KV BABUGARH CANTT.');
INSERT INTO school (id, school_name) VALUES ( 279, 'KV BADARWAH');
INSERT INTO school (id, school_name) VALUES ( 280, 'KV BADAUN');
INSERT INTO school (id, school_name) VALUES ( 281, 'KV BADDOWAL CANTT');
INSERT INTO school (id, school_name) VALUES ( 282, 'KV BADWANI');
INSERT INTO school (id, school_name) VALUES ( 283, 'KV BAGALKOT');
INSERT INTO school (id, school_name) VALUES ( 284, 'KV BAGDOGRA');
INSERT INTO school (id, school_name) VALUES ( 285, 'KV BAGESHWAR');
INSERT INTO school (id, school_name) VALUES ( 286, 'KV BAIRAGARH');
INSERT INTO school (id, school_name) VALUES ( 287, 'KV BAKLOH');
INSERT INTO school (id, school_name) VALUES ( 288, 'KV BALAGHAT');
INSERT INTO school (id, school_name) VALUES ( 289, 'KV BALASORE');
INSERT INTO school (id, school_name) VALUES ( 290, 'KV BALIGUNGE');
INSERT INTO school (id, school_name) VALUES ( 291, 'KV BALLIYA');
INSERT INTO school (id, school_name) VALUES ( 292, 'KV BALRAMPUR');
INSERT INTO school (id, school_name) VALUES ( 293, 'KV BAMANGACHI');
INSERT INTO school (id, school_name) VALUES ( 294, 'KV BAMBOLIM CAMP');
INSERT INTO school (id, school_name) VALUES ( 295, 'KV BANAR');
INSERT INTO school (id, school_name) VALUES ( 296, 'KV BANDEL RAILWAY COLONY');
INSERT INTO school (id, school_name) VALUES ( 297, 'KV BANDIKUI');
INSERT INTO school (id, school_name) VALUES ( 298, 'KV BANGANA');
INSERT INTO school (id, school_name) VALUES ( 299, 'KV BANKA');
INSERT INTO school (id, school_name) VALUES ( 300, 'KV BANSWARA');
INSERT INTO school (id, school_name) VALUES ( 301, 'KV BAOLI BAGHPAT');
INSERT INTO school (id, school_name) VALUES ( 302, 'KV BARABANKI');
INSERT INTO school (id, school_name) VALUES ( 303, 'KV BARAMULA');
INSERT INTO school (id, school_name) VALUES ( 304, 'KV BARAN');
INSERT INTO school (id, school_name) VALUES ( 305, 'KV BARGARH');
INSERT INTO school (id, school_name) VALUES ( 306, 'KV BARIMUL');
INSERT INTO school (id, school_name) VALUES ( 307, 'KV BARIPADA');
INSERT INTO school (id, school_name) VALUES ( 308, 'KV BARKAKANA');
INSERT INTO school (id, school_name) VALUES ( 309, 'KV BARPETA');
INSERT INTO school (id, school_name) VALUES ( 310, 'KV BASOLI (LAKHANPUR)');
INSERT INTO school (id, school_name) VALUES ( 311, 'KV BASTI');
INSERT INTO school (id, school_name) VALUES ( 312, 'KV BEAWAR');
INSERT INTO school (id, school_name) VALUES ( 313, 'KV BEG &amp; CENTRE KHADKI PUNE');
INSERT INTO school (id, school_name) VALUES ( 314, 'KV BELLARY');
INSERT INTO school (id, school_name) VALUES ( 315, 'KV BEML NAGAR KOLAR');
INSERT INTO school (id, school_name) VALUES ( 316, 'KV BENGDUBI');
INSERT INTO school (id, school_name) VALUES ( 317, 'KV BERHAMPORE');
INSERT INTO school (id, school_name) VALUES ( 318, 'KV BERHAMPUR');
INSERT INTO school (id, school_name) VALUES ( 319, 'KV BETIAH');
INSERT INTO school (id, school_name) VALUES ( 320, 'KV BETUL');
INSERT INTO school (id, school_name) VALUES ( 321, 'KV BHADOHI');
INSERT INTO school (id, school_name) VALUES ( 322, 'KV BHADRAK');
INSERT INTO school (id, school_name) VALUES ( 323, 'KV BHAKLI');
INSERT INTO school (id, school_name) VALUES ( 324, 'KV BHANALA');
INSERT INTO school (id, school_name) VALUES ( 325, 'KV BHANDARA');
INSERT INTO school (id, school_name) VALUES ( 326, 'KV BHANDUP');
INSERT INTO school (id, school_name) VALUES ( 327, 'KV BHANJNAGAR');
INSERT INTO school (id, school_name) VALUES ( 328, 'KV BHARATPUR');
INSERT INTO school (id, school_name) VALUES ( 329, 'KV BHAVNAGAR PARA');
INSERT INTO school (id, school_name) VALUES ( 330, 'KV BHAWANI PATNA');
INSERT INTO school (id, school_name) VALUES ( 331, 'KV BHEL HARDWAR');
INSERT INTO school (id, school_name) VALUES ( 332, 'KV BHILAI');
INSERT INTO school (id, school_name) VALUES ( 333, 'KV BHILWARA');
INSERT INTO school (id, school_name) VALUES ( 334, 'KV BHIMTAL');
INSERT INTO school (id, school_name) VALUES ( 335, 'KV BHIND');
INSERT INTO school (id, school_name) VALUES ( 336, 'KV BHONGIR');
INSERT INTO school (id, school_name) VALUES ( 337, 'KV BHUNGA');
INSERT INTO school (id, school_name) VALUES ( 338, 'KV BHURKUNDA');
INSERT INTO school (id, school_name) VALUES ( 339, 'KV BIJAPUR');
INSERT INTO school (id, school_name) VALUES ( 340, 'KV BILASPUR');
INSERT INTO school (id, school_name) VALUES ( 341, 'KV BINA');
INSERT INTO school (id, school_name) VALUES ( 342, 'KV BIRBHUM');
INSERT INTO school (id, school_name) VALUES ( 343, 'KV BIRPUR DEHRADUN');
INSERT INTO school (id, school_name) VALUES ( 344, 'KV BODHAN TOWN');
INSERT INTO school (id, school_name) VALUES ( 345, 'KV BOLPUR');
INSERT INTO school (id, school_name) VALUES ( 346, 'KV BONDAMUNDA');
INSERT INTO school (id, school_name) VALUES ( 347, 'KV BORJHAR');
INSERT INTO school (id, school_name) VALUES ( 348, 'KV BOUDH');
INSERT INTO school (id, school_name) VALUES ( 349, 'KV BRBNMPL MYSURU');
INSERT INTO school (id, school_name) VALUES ( 350, 'KV BUDAYAN JIND');
INSERT INTO school (id, school_name) VALUES ( 351, 'KV BULANDSHAHAR');
INSERT INTO school (id, school_name) VALUES ( 352, 'KV BUNDI');
INSERT INTO school (id, school_name) VALUES ( 353, 'KV BURDWAN');
INSERT INTO school (id, school_name) VALUES ( 354, 'KV BURHANPUR');
INSERT INTO school (id, school_name) VALUES ( 355, 'KV BUXAR');
INSERT INTO school (id, school_name) VALUES ( 356, 'KV BVFCL NAMRUP');
INSERT INTO school (id, school_name) VALUES ( 357, 'KV CANTT No.1 DELHI');
INSERT INTO school (id, school_name) VALUES ( 358, 'KV CANTT. No.1 FEROZEPUR');
INSERT INTO school (id, school_name) VALUES ( 359, 'KV CAST WHEEL PLANT BELA');
INSERT INTO school (id, school_name) VALUES ( 360, 'KV CECRI KARAIKUDI');
INSERT INTO school (id, school_name) VALUES ( 361, 'KV CENTRAL UNIVERISTY OF JAMMU');
INSERT INTO school (id, school_name) VALUES ( 362, 'KV CENTRAL UNIVERSITY OF RAJASTHAN. BANDERSINDRI');
INSERT INTO school (id, school_name) VALUES ( 363, 'KV CENTRAL UNIVERSITY OF TAMILNADU');
INSERT INTO school (id, school_name) VALUES ( 364, 'KV CHABUA');
INSERT INTO school (id, school_name) VALUES ( 365, 'KV CHAKPIKARONG');
INSERT INTO school (id, school_name) VALUES ( 366, 'KV CHAKRADHARPUR');
INSERT INTO school (id, school_name) VALUES ( 367, 'KV CHAMPHAI');
INSERT INTO school (id, school_name) VALUES ( 368, 'KV CHAMRAJ NAGAR');
INSERT INTO school (id, school_name) VALUES ( 369, 'KV CHANDA');
INSERT INTO school (id, school_name) VALUES ( 370, 'KV CHANDERI FATEHABAD');
INSERT INTO school (id, school_name) VALUES ( 371, 'KV CHANNAPATNA');
INSERT INTO school (id, school_name) VALUES ( 372, 'KV CHAPRA');
INSERT INTO school (id, school_name) VALUES ( 373, 'KV CHATRA');
INSERT INTO school (id, school_name) VALUES ( 374, 'KV CHAURAI');
INSERT INTO school (id, school_name) VALUES ( 375, 'KV CHENANI');
INSERT INTO school (id, school_name) VALUES ( 376, 'KV CHENNEERKARA');
INSERT INTO school (id, school_name) VALUES ( 377, 'KV CHERO SALEMPUR');
INSERT INTO school (id, school_name) VALUES ( 378, 'KV CHHABRA THERMAL POWER PROJECT (CTPS)');
INSERT INTO school (id, school_name) VALUES ( 379, 'KV CHHATTARPUR');
INSERT INTO school (id, school_name) VALUES ( 380, 'KV CHHINDWARA');
INSERT INTO school (id, school_name) VALUES ( 381, 'KV CHIKODI');
INSERT INTO school (id, school_name) VALUES ( 382, 'KV CHITRAKOOT');
INSERT INTO school (id, school_name) VALUES ( 383, 'KV CHITTORGARH');
INSERT INTO school (id, school_name) VALUES ( 384, 'KV CHOPAN');
INSERT INTO school (id, school_name) VALUES ( 385, 'KV CHURU');
INSERT INTO school (id, school_name) VALUES ( 386, 'KV CLRI CHENNAI');
INSERT INTO school (id, school_name) VALUES ( 387, 'KV CME PUNE');
INSERT INTO school (id, school_name) VALUES ( 388, 'KV COD CHHEOKI');
INSERT INTO school (id, school_name) VALUES ( 389, 'KV COIMBATORE');
INSERT INTO school (id, school_name) VALUES ( 390, 'KV COOCH BEHAR');
INSERT INTO school (id, school_name) VALUES ( 391, 'KV COSSIPORE');
INSERT INTO school (id, school_name) VALUES ( 392, 'KV CPCRI No.1 KASRAGOD');
INSERT INTO school (id, school_name) VALUES ( 393, 'KV CUTTACK');
INSERT INTO school (id, school_name) VALUES ( 394, 'KV DABRA');
INSERT INTO school (id, school_name) VALUES ( 395, 'KV DAHOD');
INSERT INTO school (id, school_name) VALUES ( 396, 'KV DAKSHIN DINAJPUR');
INSERT INTO school (id, school_name) VALUES ( 397, 'KV DAMOH');
INSERT INTO school (id, school_name) VALUES ( 398, 'KV DANAPUR CANTT');
INSERT INTO school (id, school_name) VALUES ( 399, 'KV DANTEWADA');
INSERT INTO school (id, school_name) VALUES ( 400, 'KV DAPORIJO');
INSERT INTO school (id, school_name) VALUES ( 401, 'KV DAPPAR');
INSERT INTO school (id, school_name) VALUES ( 402, 'KV DATIA');
INSERT INTO school (id, school_name) VALUES ( 403, 'KV DAUSA');
INSERT INTO school (id, school_name) VALUES ( 404, 'KV DAVANGERE');
INSERT INTO school (id, school_name) VALUES ( 405, 'KV DCW No.2 PATIALA');
INSERT INTO school (id, school_name) VALUES ( 406, 'KV DEEPATOLI RANCHI');
INSERT INTO school (id, school_name) VALUES ( 407, 'KV DEHRADUN CANTT UPPER CAMP');
INSERT INTO school (id, school_name) VALUES ( 408, 'KV DEHRADUN OLF');
INSERT INTO school (id, school_name) VALUES ( 409, 'KV DEOGARH');
INSERT INTO school (id, school_name) VALUES ( 410, 'KV DEORIA');
INSERT INTO school (id, school_name) VALUES ( 411, 'KV DEVGARH');
INSERT INTO school (id, school_name) VALUES ( 412, 'KV DEWAS');
INSERT INTO school (id, school_name) VALUES ( 413, 'KV DGI COMPLEX');
INSERT INTO school (id, school_name) VALUES ( 414, 'KV DHALAI');
INSERT INTO school (id, school_name) VALUES ( 415, 'KV DHAMANA');
INSERT INTO school (id, school_name) VALUES ( 416, 'KV DHAMTARI');
INSERT INTO school (id, school_name) VALUES ( 417, 'KV DHANA');
INSERT INTO school (id, school_name) VALUES ( 418, 'KV DHANBAD OLD DVS BUILDING');
INSERT INTO school (id, school_name) VALUES ( 419, 'KV DHAR');
INSERT INTO school (id, school_name) VALUES ( 420, 'KV DHARAMGARH');
INSERT INTO school (id, school_name) VALUES ( 421, 'KV DHARAMSHALA CANTT');
INSERT INTO school (id, school_name) VALUES ( 422, 'KV DHARANGANDHRA');
INSERT INTO school (id, school_name) VALUES ( 423, 'KV DHARMAPURI');
INSERT INTO school (id, school_name) VALUES ( 424, 'KV DHARWAD');
INSERT INTO school (id, school_name) VALUES ( 425, 'KV DHENKANAL TOWN');
INSERT INTO school (id, school_name) VALUES ( 426, 'KV DHOLPUR');
INSERT INTO school (id, school_name) VALUES ( 427, 'KV DHULE');
INSERT INTO school (id, school_name) VALUES ( 428, 'KV DIBRUGARH');
INSERT INTO school (id, school_name) VALUES ( 429, 'KV DIGAPAHANDI');
INSERT INTO school (id, school_name) VALUES ( 430, 'KV DINDORI');
INSERT INTO school (id, school_name) VALUES ( 431, 'KV DINJAN');
INSERT INTO school (id, school_name) VALUES ( 432, 'KV DIPHU');
INSERT INTO school (id, school_name) VALUES ( 433, 'KV DIRANG');
INSERT INTO school (id, school_name) VALUES ( 434, 'KV DIU');
INSERT INTO school (id, school_name) VALUES ( 435, 'KV DL MEERUT CANTT');
INSERT INTO school (id, school_name) VALUES ( 436, 'KV DODA JODHPUR');
INSERT INTO school (id, school_name) VALUES ( 437, 'KV DR. RAJENDRA PRASAD');
INSERT INTO school (id, school_name) VALUES ( 438, 'KV DRDO BANGALORE');
INSERT INTO school (id, school_name) VALUES ( 439, 'KV DUM-DUM');
INSERT INTO school (id, school_name) VALUES ( 440, 'KV DUMKA');
INSERT INTO school (id, school_name) VALUES ( 441, 'KV DUNGAR PUR');
INSERT INTO school (id, school_name) VALUES ( 442, 'KV DUNGARGARH');
INSERT INTO school (id, school_name) VALUES ( 443, 'KV DURG');
INSERT INTO school (id, school_name) VALUES ( 444, 'KV DWARKA');
INSERT INTO school (id, school_name) VALUES ( 445, 'KV EAC UPPER SHILLONG');
INSERT INTO school (id, school_name) VALUES ( 446, 'KV ELURU');
INSERT INTO school (id, school_name) VALUES ( 447, 'KV ERNAKULAM');
INSERT INTO school (id, school_name) VALUES ( 448, 'KV ETAH');
INSERT INTO school (id, school_name) VALUES ( 449, 'KV ETAWA');
INSERT INTO school (id, school_name) VALUES ( 450, 'KV EZHIMALA');
INSERT INTO school (id, school_name) VALUES ( 451, 'KV FAIZABAD CANTT');
INSERT INTO school (id, school_name) VALUES ( 452, 'KV FARidKOT');
INSERT INTO school (id, school_name) VALUES ( 453, 'KV FATEH GARH');
INSERT INTO school (id, school_name) VALUES ( 454, 'KV FATEHABAD');
INSERT INTO school (id, school_name) VALUES ( 455, 'KV FORT WILLIAM');
INSERT INTO school (id, school_name) VALUES ( 456, 'KV FRI DEHRADUN');
INSERT INTO school (id, school_name) VALUES ( 457, 'KV GACHIBAWLI');
INSERT INTO school (id, school_name) VALUES ( 458, 'KV GAIL JHABUA');
INSERT INTO school (id, school_name) VALUES ( 459, 'KV GAIL VIJAYAPUR');
INSERT INTO school (id, school_name) VALUES ( 460, 'KV GAJAPATI');
INSERT INTO school (id, school_name) VALUES ( 461, 'KV GANDHIGRAM');
INSERT INTO school (id, school_name) VALUES ( 462, 'KV GANESH KHIND');
INSERT INTO school (id, school_name) VALUES ( 463, 'KV GANGAPUR CITY');
INSERT INTO school (id, school_name) VALUES ( 464, 'KV GANGAVATHI');
INSERT INTO school (id, school_name) VALUES ( 465, 'KV GANGRANI');
INSERT INTO school (id, school_name) VALUES ( 466, 'KV GANGTOK');
INSERT INTO school (id, school_name) VALUES ( 467, 'KV GANJ BASODA');
INSERT INTO school (id, school_name) VALUES ( 468, 'KV GARDEN REACH');
INSERT INTO school (id, school_name) VALUES ( 469, 'KV GARHA');
INSERT INTO school (id, school_name) VALUES ( 470, 'KV GARHARA');
INSERT INTO school (id, school_name) VALUES ( 471, 'KV GARHARA');
INSERT INTO school (id, school_name) VALUES ( 472, 'KV GARHWA');
INSERT INTO school (id, school_name) VALUES ( 473, 'KV GAURIBidANUR');
INSERT INTO school (id, school_name) VALUES ( 474, 'KV GC (CRPF) AGARTALA');
INSERT INTO school (id, school_name) VALUES ( 475, 'KV GC (CRPF) SILIGURI');
INSERT INTO school (id, school_name) VALUES ( 476, 'KV GC (CRPF) SONEPAT');
INSERT INTO school (id, school_name) VALUES ( 477, 'KV GCF No.1 JABALPUR');
INSERT INTO school (id, school_name) VALUES ( 478, 'KV GCF No.2 JABALPUR');
INSERT INTO school (id, school_name) VALUES ( 479, 'KV GERUKAMUKH HE PROJECT');
INSERT INTO school (id, school_name) VALUES ( 480, 'KV GHATKESAR NUCLEAR FUEL COMPLEX.');
INSERT INTO school (id, school_name) VALUES ( 481, 'KV GHAZIABAD');
INSERT INTO school (id, school_name) VALUES ( 482, 'KV GHAZIPUR');
INSERT INTO school (id, school_name) VALUES ( 483, 'KV GHUMARWIN');
INSERT INTO school (id, school_name) VALUES ( 484, 'KV GILL NAGAR CHENNAI');
INSERT INTO school (id, school_name) VALUES ( 485, 'KV GIRidIH');
INSERT INTO school (id, school_name) VALUES ( 486, 'KV GOALPARA');
INSERT INTO school (id, school_name) VALUES ( 487, 'KV GODDA');
INSERT INTO school (id, school_name) VALUES ( 488, 'KV GODHRA');
INSERT INTO school (id, school_name) VALUES ( 489, 'KV GOLAGHAT');
INSERT INTO school (id, school_name) VALUES ( 490, 'KV GOLDEN ROCK');
INSERT INTO school (id, school_name) VALUES ( 491, 'KV GOLE MARKET');
INSERT INTO school (id, school_name) VALUES ( 492, 'KV GOMOH');
INSERT INTO school (id, school_name) VALUES ( 493, 'KV GOMTI NAGAR');
INSERT INTO school (id, school_name) VALUES ( 494, 'KV GONDA');
INSERT INTO school (id, school_name) VALUES ( 495, 'KV GOOTY ANANTPUR');
INSERT INTO school (id, school_name) VALUES ( 496, 'KV GOPALGANJ');
INSERT INTO school (id, school_name) VALUES ( 497, 'KV GOPALPUR CANTT.');
INSERT INTO school (id, school_name) VALUES ( 498, 'KV GOPESHWAR');
INSERT INTO school (id, school_name) VALUES ( 499, 'KV GOVINDPUR (BSF)');
INSERT INTO school (id, school_name) VALUES ( 500, 'KV GREATER NOidA');
INSERT INTO school (id, school_name) VALUES ( 501, 'KV GULBARGA KALABURAGI');
INSERT INTO school (id, school_name) VALUES ( 502, 'KV GUMLA');
INSERT INTO school (id, school_name) VALUES ( 503, 'KV GUNA');
INSERT INTO school (id, school_name) VALUES ( 504, 'KV GUNA');
INSERT INTO school (id, school_name) VALUES ( 505, 'KV GUNTAKAL');
INSERT INTO school (id, school_name) VALUES ( 506, 'KV GUNTUR');
INSERT INTO school (id, school_name) VALUES ( 507, 'KV GUNUPUR');
INSERT INTO school (id, school_name) VALUES ( 508, 'KV HAJIPUR');
INSERT INTO school (id, school_name) VALUES ( 509, 'KV HAJIRA No.2 SURAT');
INSERT INTO school (id, school_name) VALUES ( 510, 'KV HALDWANI CANTT');
INSERT INTO school (id, school_name) VALUES ( 511, 'KV HAMIRPUR');
INSERT INTO school (id, school_name) VALUES ( 512, 'KV HANUMANGARH');
INSERT INTO school (id, school_name) VALUES ( 513, 'KV HARDA');
INSERT INTO school (id, school_name) VALUES ( 514, 'KV HARDOI');
INSERT INTO school (id, school_name) VALUES ( 515, 'KV HARNAUT');
INSERT INTO school (id, school_name) VALUES ( 516, 'KV HARSINGPURA');
INSERT INTO school (id, school_name) VALUES ( 517, 'KV HASIMARA');
INSERT INTO school (id, school_name) VALUES ( 518, 'KV HASSAN');
INSERT INTO school (id, school_name) VALUES ( 519, 'KV HATHRAS');
INSERT INTO school (id, school_name) VALUES ( 520, 'KV HATTA NAGAR');
INSERT INTO school (id, school_name) VALUES ( 521, 'KV HAVERI');
INSERT INTO school (id, school_name) VALUES ( 522, 'KV HBK No.1 DEHRADUN');
INSERT INTO school (id, school_name) VALUES ( 523, 'KV HBK No.2 DEHRADUN');
INSERT INTO school (id, school_name) VALUES ( 524, 'KV HEBBAL BANGALORE');
INSERT INTO school (id, school_name) VALUES ( 525, 'KV HEMAMBIKA NAGAR No.1 PALAKKAD');
INSERT INTO school (id, school_name) VALUES ( 526, 'KV HIGH GROUNDS');
INSERT INTO school (id, school_name) VALUES ( 527, 'KV HIMMAT NAGAR');
INSERT INTO school (id, school_name) VALUES ( 528, 'KV HINJILICUT');
INSERT INTO school (id, school_name) VALUES ( 529, 'KV HIRANAGAR');
INSERT INTO school (id, school_name) VALUES ( 530, 'KV HISSAR CANTT');
INSERT INTO school (id, school_name) VALUES ( 531, 'KV HOSHANGABAD');
INSERT INTO school (id, school_name) VALUES ( 532, 'KV HOSPET');
INSERT INTO school (id, school_name) VALUES ( 533, 'KV HPF OOTACAMUND');
INSERT INTO school (id, school_name) VALUES ( 534, 'KV HUTTI');
INSERT INTO school (id, school_name) VALUES ( 535, 'KV HVF AVADI');
INSERT INTO school (id, school_name) VALUES ( 536, 'KV HYDERABAD CENTRAL UNIVERSITY');
INSERT INTO school (id, school_name) VALUES ( 537, 'KV I STC JABALPUR');
INSERT INTO school (id, school_name) VALUES ( 538, 'KV IAT GIRINAGAR');
INSERT INTO school (id, school_name) VALUES ( 539, 'KV IFFCO GANDHidHAM');
INSERT INTO school (id, school_name) VALUES ( 540, 'KV IIIT ALLAHABAD');
INSERT INTO school (id, school_name) VALUES ( 541, 'KV IIM CAMPUS');
INSERT INTO school (id, school_name) VALUES ( 542, 'KV IIM JOKA');
INSERT INTO school (id, school_name) VALUES ( 543, 'KV IIP DEHRADUN');
INSERT INTO school (id, school_name) VALUES ( 544, 'KV IISC BANGALORE');
INSERT INTO school (id, school_name) VALUES ( 545, 'KV IIT CHENNAI');
INSERT INTO school (id, school_name) VALUES ( 546, 'KV IIT GUWAHATI');
INSERT INTO school (id, school_name) VALUES ( 547, 'KV IIT JODHPUR');
INSERT INTO school (id, school_name) VALUES ( 548, 'KV IIT PATNA');
INSERT INTO school (id, school_name) VALUES ( 549, 'KV IIT POWAI');
INSERT INTO school (id, school_name) VALUES ( 550, 'KV IMA DEHRADUN');
INSERT INTO school (id, school_name) VALUES ( 551, 'KV INA COLONY');
INSERT INTO school (id, school_name) VALUES ( 552, 'KV INDERPURA');
INSERT INTO school (id, school_name) VALUES ( 553, 'KV INDRA GANDHI NATIONAL TRIBAL UNIVERSITY');
INSERT INTO school (id, school_name) VALUES ( 554, 'KV INS CHILKA');
INSERT INTO school (id, school_name) VALUES ( 555, 'KV INS DRONACHARYA No.4 COCHIN');
INSERT INTO school (id, school_name) VALUES ( 556, 'KV INS HAMLA');
INSERT INTO school (id, school_name) VALUES ( 557, 'KV INS KALINGA BHEEMUNIPATNAM');
INSERT INTO school (id, school_name) VALUES ( 558, 'KV INS VALSURA');
INSERT INTO school (id, school_name) VALUES ( 559, 'KV INS VIJAYANARAYANAM');
INSERT INTO school (id, school_name) VALUES ( 560, 'KV IOC GUWAHATI');
INSERT INTO school (id, school_name) VALUES ( 561, 'KV IRLAPADU');
INSERT INTO school (id, school_name) VALUES ( 562, 'KV ISLAND GROUNDS');
INSERT INTO school (id, school_name) VALUES ( 563, 'KV ITARANA');
INSERT INTO school (id, school_name) VALUES ( 564, 'KV ITBP DEHRADUN');
INSERT INTO school (id, school_name) VALUES ( 565, 'KV ITBP GAUCHAR');
INSERT INTO school (id, school_name) VALUES ( 566, 'KV ITBP JOSHIMATH');
INSERT INTO school (id, school_name) VALUES ( 567, 'KV ITBP KARERA');
INSERT INTO school (id, school_name) VALUES ( 568, 'KV ITBP MIRTHI');
INSERT INTO school (id, school_name) VALUES ( 569, 'KV ITBP RAMGARH AMBALA');
INSERT INTO school (id, school_name) VALUES ( 570, 'KV ITBP SARHAN');
INSERT INTO school (id, school_name) VALUES ( 571, 'KV ITBP SHIVPURI');
INSERT INTO school (id, school_name) VALUES ( 572, 'KV JAGATSINGHPUR');
INSERT INTO school (id, school_name) VALUES ( 573, 'KV JAGDALPUR');
INSERT INTO school (id, school_name) VALUES ( 574, 'KV JAISINDHAR');
INSERT INTO school (id, school_name) VALUES ( 575, 'KV JAJPUR');
INSERT INTO school (id, school_name) VALUES ( 576, 'KV JALIPA CANTT');
INSERT INTO school (id, school_name) VALUES ( 577, 'KV JALORE');
INSERT INTO school (id, school_name) VALUES ( 578, 'KV JAMAI');
INSERT INTO school (id, school_name) VALUES ( 579, 'KV JAMALPUR');
INSERT INTO school (id, school_name) VALUES ( 580, 'KV JAMTARA');
INSERT INTO school (id, school_name) VALUES ( 581, 'KV JAMUNA COLLIERY');
INSERT INTO school (id, school_name) VALUES ( 582, 'KV JANAKPURI');
INSERT INTO school (id, school_name) VALUES ( 583, 'KV JANJGIR');
INSERT INTO school (id, school_name) VALUES ( 584, 'KV JASHPUR');
INSERT INTO school (id, school_name) VALUES ( 585, 'KV JASHPUR');
INSERT INTO school (id, school_name) VALUES ( 586, 'KV JAWAHAR NAGAR');
INSERT INTO school (id, school_name) VALUES ( 587, 'KV JAYANT COLLIERY');
INSERT INTO school (id, school_name) VALUES ( 588, 'KV JETPUR');
INSERT INTO school (id, school_name) VALUES ( 589, 'KV JHAJHA');
INSERT INTO school (id, school_name) VALUES ( 590, 'KV JHAJJAR');
INSERT INTO school (id, school_name) VALUES ( 591, 'KV JHALAWAR');
INSERT INTO school (id, school_name) VALUES ( 592, 'KV JHARASANGAM MEDAK');
INSERT INTO school (id, school_name) VALUES ( 593, 'KV JHARSUGUDA');
INSERT INTO school (id, school_name) VALUES ( 594, 'KV JHUNJHUNU');
INSERT INTO school (id, school_name) VALUES ( 595, 'KV JINDRAH');
INSERT INTO school (id, school_name) VALUES ( 596, 'KV JOURIAN');
INSERT INTO school (id, school_name) VALUES ( 597, 'KV JUNAGARH');
INSERT INTO school (id, school_name) VALUES ( 598, 'KV JUTOGH');
INSERT INTO school (id, school_name) VALUES ( 599, 'KV K.K. NAGAR ASHOK NAGAR');
INSERT INTO school (id, school_name) VALUES ( 600, 'KV KADAPA');
INSERT INTO school (id, school_name) VALUES ( 601, 'KV KADRIMidRI');
INSERT INTO school (id, school_name) VALUES ( 602, 'KV KADUTHURUTHY');
INSERT INTO school (id, school_name) VALUES ( 603, 'KV KAILASHAHAR');
INSERT INTO school (id, school_name) VALUES ( 604, 'KV KAKINADA');
INSERT INTO school (id, school_name) VALUES ( 605, 'KV KALIMPONG (DURBIN)');
INSERT INTO school (id, school_name) VALUES ( 606, 'KV KALPETTA');
INSERT INTO school (id, school_name) VALUES ( 607, 'KV KALUCHAK');
INSERT INTO school (id, school_name) VALUES ( 608, 'KV KAMPTEE');
INSERT INTO school (id, school_name) VALUES ( 609, 'KV KANDHAMAL');
INSERT INTO school (id, school_name) VALUES ( 610, 'KV KANDUKUR TOWN');
INSERT INTO school (id, school_name) VALUES ( 611, 'KV KANHAGAD');
INSERT INTO school (id, school_name) VALUES ( 612, 'KV KANJIKODE No.2 PALGHAT');
INSERT INTO school (id, school_name) VALUES ( 613, 'KV KANKER');
INSERT INTO school (id, school_name) VALUES ( 614, 'KV KANKINARA');
INSERT INTO school (id, school_name) VALUES ( 615, 'KV KANNUR');
INSERT INTO school (id, school_name) VALUES ( 616, 'KV KANPUR CANTT');
INSERT INTO school (id, school_name) VALUES ( 617, 'KV KANPUR RAKSHAVIHAR');
INSERT INTO school (id, school_name) VALUES ( 618, 'KV KAPURTHALA CANTT.');
INSERT INTO school (id, school_name) VALUES ( 619, 'KV KARAIKAL');
INSERT INTO school (id, school_name) VALUES ( 620, 'KV KARAULI');
INSERT INTO school (id, school_name) VALUES ( 621, 'KV KARGIL');
INSERT INTO school (id, school_name) VALUES ( 622, 'KV KARIM NAGAR');
INSERT INTO school (id, school_name) VALUES ( 623, 'KV KARIMGUNJ');
INSERT INTO school (id, school_name) VALUES ( 624, 'KV KARNAL');
INSERT INTO school (id, school_name) VALUES ( 625, 'KV KARWAR');
INSERT INTO school (id, school_name) VALUES ( 626, 'KV KASAUNI');
INSERT INTO school (id, school_name) VALUES ( 627, 'KV KASHIPUR');
INSERT INTO school (id, school_name) VALUES ( 628, 'KV KASRAWAD');
INSERT INTO school (id, school_name) VALUES ( 629, 'KV KATHMANDU');
INSERT INTO school (id, school_name) VALUES ( 630, 'KV KATHUA');
INSERT INTO school (id, school_name) VALUES ( 631, 'KV KATIHAR');
INSERT INTO school (id, school_name) VALUES ( 632, 'KV KATIHAR');
INSERT INTO school (id, school_name) VALUES ( 633, 'KV KAUHAR AMETHI');
INSERT INTO school (id, school_name) VALUES ( 634, 'KV KAVARATTI');
INSERT INTO school (id, school_name) VALUES ( 635, 'KV KEONJHAR');
INSERT INTO school (id, school_name) VALUES ( 636, 'KV KEYLONG LAHAUL SPITI');
INSERT INTO school (id, school_name) VALUES ( 637, 'KV KHAGARIA');
INSERT INTO school (id, school_name) VALUES ( 638, 'KV KHAGAUL');
INSERT INTO school (id, school_name) VALUES ( 639, 'KV KHAIRAGARH');
INSERT INTO school (id, school_name) VALUES ( 640, 'KV KHAMARIA');
INSERT INTO school (id, school_name) VALUES ( 641, 'KV KHAMMAM');
INSERT INTO school (id, school_name) VALUES ( 642, 'KV KHANAPARA');
INSERT INTO school (id, school_name) VALUES ( 643, 'KV KHANDWA');
INSERT INTO school (id, school_name) VALUES ( 644, 'KV KHANPUR');
INSERT INTO school (id, school_name) VALUES ( 645, 'KV KHARGONE');
INSERT INTO school (id, school_name) VALUES ( 646, 'KV KHATIMA');
INSERT INTO school (id, school_name) VALUES ( 647, 'KV KHETRI NAGAR');
INSERT INTO school (id, school_name) VALUES ( 648, 'KV KHICHARIPUR DELHI.');
INSERT INTO school (id, school_name) VALUES ( 649, 'KV KHONSA');
INSERT INTO school (id, school_name) VALUES ( 650, 'KV KHUNTI');
INSERT INTO school (id, school_name) VALUES ( 651, 'KV KHURDA ROAD');
INSERT INTO school (id, school_name) VALUES ( 652, 'KV KHURUD');
INSERT INTO school (id, school_name) VALUES ( 653, 'KV KIMIN (9 ASSAM RIFLES)');
INSERT INTO school (id, school_name) VALUES ( 654, 'KV KISHTWAR');
INSERT INTO school (id, school_name) VALUES ( 655, 'KV KODAGU');
INSERT INTO school (id, school_name) VALUES ( 656, 'KV KODERMA');
INSERT INTO school (id, school_name) VALUES ( 657, 'KV KOKRAJHAR');
INSERT INTO school (id, school_name) VALUES ( 658, 'KV KOLIWADA');
INSERT INTO school (id, school_name) VALUES ( 659, 'KV KOLLAM');
INSERT INTO school (id, school_name) VALUES ( 660, 'KV KONDAGAON');
INSERT INTO school (id, school_name) VALUES ( 661, 'KV KONNI');
INSERT INTO school (id, school_name) VALUES ( 662, 'KV KOPPAL');
INSERT INTO school (id, school_name) VALUES ( 663, 'KV KORAPUT');
INSERT INTO school (id, school_name) VALUES ( 664, 'KV KOTHURU');
INSERT INTO school (id, school_name) VALUES ( 665, 'KV KPA RAMAVARMAPURAM');
INSERT INTO school (id, school_name) VALUES ( 666, 'KV KRISHNARAJAPURAM');
INSERT INTO school (id, school_name) VALUES ( 667, 'KV KURNOOL');
INSERT INTO school (id, school_name) VALUES ( 668, 'KV KUTRA');
INSERT INTO school (id, school_name) VALUES ( 669, 'KV LAKHIMPUR ASSAM');
INSERT INTO school (id, school_name) VALUES ( 670, 'KV LAKHIMPUR KHERI, UP');
INSERT INTO school (id, school_name) VALUES ( 671, 'KV LAKHISA RAI');
INSERT INTO school (id, school_name) VALUES ( 672, 'KV LAKHNADON');
INSERT INTO school (id, school_name) VALUES ( 673, 'KV LALGARH JATTAN');
INSERT INTO school (id, school_name) VALUES ( 674, 'KV LALITPUR');
INSERT INTO school (id, school_name) VALUES ( 675, 'KV LANSDOWNE');
INSERT INTO school (id, school_name) VALUES ( 676, 'KV LATEHAR');
INSERT INTO school (id, school_name) VALUES ( 677, 'KV LAWRANCE ROAD KESHAVPURAM');
INSERT INTO school (id, school_name) VALUES ( 678, 'KV LEH');
INSERT INTO school (id, school_name) VALUES ( 679, 'KV LEKHA PANI');
INSERT INTO school (id, school_name) VALUES ( 680, 'KV LOHAGHAT');
INSERT INTO school (id, school_name) VALUES ( 681, 'KV LOHARDAGA');
INSERT INTO school (id, school_name) VALUES ( 682, 'KV LOKRA');
INSERT INTO school (id, school_name) VALUES ( 683, 'KV LONAVALA');
INSERT INTO school (id, school_name) VALUES ( 684, 'KV LONGDING');
INSERT INTO school (id, school_name) VALUES ( 685, 'KV LUCKNOW CANTT');
INSERT INTO school (id, school_name) VALUES ( 686, 'KV LUMDING');
INSERT INTO school (id, school_name) VALUES ( 687, 'KV LUNGLEI');
INSERT INTO school (id, school_name) VALUES ( 688, 'KV M.C.F. RAEBREILLY');
INSERT INTO school (id, school_name) VALUES ( 689, 'KV MACHHLIPATNAM');
INSERT INTO school (id, school_name) VALUES ( 690, 'KV MADHUPUR(DEOGHAR)');
INSERT INTO school (id, school_name) VALUES ( 691, 'KV MAHABUBABAD');
INSERT INTO school (id, school_name) VALUES ( 692, 'KV MAHABUBNAGAR');
INSERT INTO school (id, school_name) VALUES ( 693, 'KV MAHARAJGANJ');
INSERT INTO school (id, school_name) VALUES ( 694, 'KV MAHARAJPUR KAWARDHA');
INSERT INTO school (id, school_name) VALUES ( 695, 'KV MAHASUMAND');
INSERT INTO school (id, school_name) VALUES ( 696, 'KV MAHATAMA GANDHI ANTARASHTRIYA HINDI VISHAV VidYALAYA');
INSERT INTO school (id, school_name) VALUES ( 697, 'KV MAHE');
INSERT INTO school (id, school_name) VALUES ( 698, 'KV MAHOBA');
INSERT INTO school (id, school_name) VALUES ( 699, 'KV MAHULDIHA');
INSERT INTO school (id, school_name) VALUES ( 700, 'KV MALANJKHAND');
INSERT INTO school (id, school_name) VALUES ( 701, 'KV MALIGAON');
INSERT INTO school (id, school_name) VALUES ( 702, 'KV MALKANGIRI');
INSERT INTO school (id, school_name) VALUES ( 703, 'KV MALKAPURAM');
INSERT INTO school (id, school_name) VALUES ( 705, 'KV MALLESHWARAM');
INSERT INTO school (id, school_name) VALUES ( 706, 'KV MANAURI ALLAHABAD');
INSERT INTO school (id, school_name) VALUES ( 707, 'KV MANCHERIAL');
INSERT INTO school (id, school_name) VALUES ( 708, 'KV MANDAPAM CAMP');
INSERT INTO school (id, school_name) VALUES ( 709, 'KV MANDI');
INSERT INTO school (id, school_name) VALUES ( 710, 'KV MANDLA');
INSERT INTO school (id, school_name) VALUES ( 711, 'KV MANDSAUR');
INSERT INTO school (id, school_name) VALUES ( 712, 'KV MANDYA');
INSERT INTO school (id, school_name) VALUES ( 713, 'KV MANENDRAGARH');
INSERT INTO school (id, school_name) VALUES ( 714, 'KV MANGALDOI');
INSERT INTO school (id, school_name) VALUES ( 715, 'KV MANKHURD');
INSERT INTO school (id, school_name) VALUES ( 716, 'KV MANMAD');
INSERT INTO school (id, school_name) VALUES ( 717, 'KV MASHRAK');
INSERT INTO school (id, school_name) VALUES ( 718, 'KV MASIMPUR');
INSERT INTO school (id, school_name) VALUES ( 719, 'KV MASJid MOTH');
INSERT INTO school (id, school_name) VALUES ( 720, 'KV MATANHAIL');
INSERT INTO school (id, school_name) VALUES ( 721, 'KV MATHANA');
INSERT INTO school (id, school_name) VALUES ( 722, 'KV MATHURA BAAD');
INSERT INTO school (id, school_name) VALUES ( 723, 'KV MATHURA CANTT');
INSERT INTO school (id, school_name) VALUES ( 724, 'KV MATI AKABARPUR');
INSERT INTO school (id, school_name) VALUES ( 725, 'KV MAU');
INSERT INTO school (id, school_name) VALUES ( 726, 'KV MEDAK');
INSERT INTO school (id, school_name) VALUES ( 727, 'KV MEG &amp; CENTRE BANGALORE');
INSERT INTO school (id, school_name) VALUES ( 728, 'KV MG RLY. BANGALORE');
INSERT INTO school (id, school_name) VALUES ( 729, 'KV MHOW');
INSERT INTO school (id, school_name) VALUES ( 730, 'KV MIAON');
INSERT INTO school (id, school_name) VALUES ( 731, 'KV MINAMBAKKAM');
INSERT INTO school (id, school_name) VALUES ( 732, 'KV MIRAN SAHIB');
INSERT INTO school (id, school_name) VALUES ( 733, 'KV MIRYALAGUDA');
INSERT INTO school (id, school_name) VALUES ( 734, 'KV MIRZAPUR');
INSERT INTO school (id, school_name) VALUES ( 735, 'KV MISA CANTT. NOWGAON');
INSERT INTO school (id, school_name) VALUES ( 736, 'KV MISSAMARI');
INSERT INTO school (id, school_name) VALUES ( 737, 'KV MIZORAM UNIVERSITY TANHRIL');
INSERT INTO school (id, school_name) VALUES ( 738, 'KV MOHALI');
INSERT INTO school (id, school_name) VALUES ( 739, 'KV MOHANBARI');
INSERT INTO school (id, school_name) VALUES ( 740, 'KV MOSCOW');
INSERT INTO school (id, school_name) VALUES ( 741, 'KV MOTIHARI');
INSERT INTO school (id, school_name) VALUES ( 742, 'KV MRP MATHURA');
INSERT INTO school (id, school_name) VALUES ( 743, 'KV MUGHAL SARAI');
INSERT INTO school (id, school_name) VALUES ( 744, 'KV MULLANPUR GARIBDAS');
INSERT INTO school (id, school_name) VALUES ( 745, 'KV MULTAI');
INSERT INTO school (id, school_name) VALUES ( 746, 'KV MUNGAOLI');
INSERT INTO school (id, school_name) VALUES ( 748, 'KV MURAD NAGAR');
INSERT INTO school (id, school_name) VALUES ( 749, 'KV MURENA');
INSERT INTO school (id, school_name) VALUES ( 750, 'KV MURGABADI');
INSERT INTO school (id, school_name) VALUES ( 751, 'KV MUSSOORIE');
INSERT INTO school (id, school_name) VALUES ( 752, 'KV MUZAFFAR NAGAR');
INSERT INTO school (id, school_name) VALUES ( 753, 'KV MUZZAFFARPUR');
INSERT INTO school (id, school_name) VALUES ( 754, 'KV MYSORE');
INSERT INTO school (id, school_name) VALUES ( 755, 'KV NABHA CANTT.');
INSERT INTO school (id, school_name) VALUES ( 756, 'KV NABINAGAR NPGCL');
INSERT INTO school (id, school_name) VALUES ( 757, 'KV NABRANGPUR');
INSERT INTO school (id, school_name) VALUES ( 758, 'KV NAD KARANJA');
INSERT INTO school (id, school_name) VALUES ( 759, 'KV NAD VISHAKHAPATNAM');
INSERT INTO school (id, school_name) VALUES ( 760, 'KV NADAUN (HP)');
INSERT INTO school (id, school_name) VALUES ( 761, 'KV NADIA (RANAGHAT)');
INSERT INTO school (id, school_name) VALUES ( 762, 'KV NAGALAND UNIVERISTY LUMAMI');
INSERT INTO school (id, school_name) VALUES ( 763, 'KV NAGAON');
INSERT INTO school (id, school_name) VALUES ( 764, 'KV NAGARCOIL');
INSERT INTO school (id, school_name) VALUES ( 765, 'KV NAGAUR');
INSERT INTO school (id, school_name) VALUES ( 766, 'KV NAGROTA');
INSERT INTO school (id, school_name) VALUES ( 767, 'KV NAHARA');
INSERT INTO school (id, school_name) VALUES ( 768, 'KV NAINI');
INSERT INTO school (id, school_name) VALUES ( 769, 'KV NAL BANGALORE');
INSERT INTO school (id, school_name) VALUES ( 770, 'KV NALANDA');
INSERT INTO school (id, school_name) VALUES ( 771, 'KV NALETI');
INSERT INTO school (id, school_name) VALUES ( 772, 'KV NALGONDA');
INSERT INTO school (id, school_name) VALUES ( 773, 'KV NAMSAI');
INSERT INTO school (id, school_name) VALUES ( 774, 'KV NANGAL BHUR');
INSERT INTO school (id, school_name) VALUES ( 775, 'KV NARANGI');
INSERT INTO school (id, school_name) VALUES ( 776, 'KV NARAYANPUR');
INSERT INTO school (id, school_name) VALUES ( 777, 'KV NARELA');
INSERT INTO school (id, school_name) VALUES ( 778, 'KV NARSING PUR');
INSERT INTO school (id, school_name) VALUES ( 779, 'KV NASIRABAD');
INSERT INTO school (id, school_name) VALUES ( 780, 'KV NAVAL BASE No.1 COCHIN');
INSERT INTO school (id, school_name) VALUES ( 781, 'KV NAYA RAIPUR');
INSERT INTO school (id, school_name) VALUES ( 782, 'KV NAYAGAON CRPF');
INSERT INTO school (id, school_name) VALUES ( 783, 'KV NAYAGARH');
INSERT INTO school (id, school_name) VALUES ( 784, 'KV NDMC DONIMALAI');
INSERT INTO school (id, school_name) VALUES ( 785, 'KV NDRF No.3 MUNDALI');
INSERT INTO school (id, school_name) VALUES ( 786, 'KV NEPA NAGAR');
INSERT INTO school (id, school_name) VALUES ( 787, 'KV NEW BONGAIGAON');
INSERT INTO school (id, school_name) VALUES ( 788, 'KV NEW CANTT ALLAHABAD');
INSERT INTO school (id, school_name) VALUES ( 789, 'KV NEW FRIENDS CENTRE VIGYAN VIHAR');
INSERT INTO school (id, school_name) VALUES ( 790, 'KV NEW MEHRAULI ROAD JNU');
INSERT INTO school (id, school_name) VALUES ( 791, 'KV NEW TEHRI TOWN');
INSERT INTO school (id, school_name) VALUES ( 793, 'KV NEYVELI LIGNITE CORPORATION');
INSERT INTO school (id, school_name) VALUES ( 794, 'KV NFR NEW JALPAIGURI');
INSERT INTO school (id, school_name) VALUES ( 795, 'KV NHDC NARMADA NAGAR');
INSERT INTO school (id, school_name) VALUES ( 796, 'KV NHPC DALHOUSIE CANTT BANIKHET');
INSERT INTO school (id, school_name) VALUES ( 797, 'KV NHPC DHARCHULA');
INSERT INTO school (id, school_name) VALUES ( 798, 'KV NHPC No.1 HEP CHAMERA');
INSERT INTO school (id, school_name) VALUES ( 799, 'KV NHPC No.2 BANBASA');
INSERT INTO school (id, school_name) VALUES ( 800, 'KV NHPC SINGTAM');
INSERT INTO school (id, school_name) VALUES ( 801, 'KV NHPC. LOKTAK');
INSERT INTO school (id, school_name) VALUES ( 802, 'KV NILESHWAR');
INSERT INTO school (id, school_name) VALUES ( 803, 'KV NIRJULI (NERIST)');
INSERT INTO school (id, school_name) VALUES ( 805, 'KV NIT AGARTALA');
INSERT INTO school (id, school_name) VALUES ( 806, 'KV NIZAMABAD');
INSERT INTO school (id, school_name) VALUES ( 807, 'KV No. III GANDHINAGAR CANTT');
INSERT INTO school (id, school_name) VALUES ( 808, 'KV No.1 (AFS) JAMNAGAR');
INSERT INTO school (id, school_name) VALUES ( 809, 'KV No.1 (PRATAP NAGAR) UDAIPUR');
INSERT INTO school (id, school_name) VALUES ( 810, 'KV No.1 (SAGAR ROAD) Bikaner');
INSERT INTO school (id, school_name) VALUES ( 811, 'KV No.1 ADAMPUR');
INSERT INTO school (id, school_name) VALUES ( 812, 'KV No.1 AHMEDNAGAR');
INSERT INTO school (id, school_name) VALUES ( 813, 'KV No.1 AKHNOOR');
INSERT INTO school (id, school_name) VALUES ( 814, 'KV No.1 AMBALA CANTT');
INSERT INTO school (id, school_name) VALUES ( 815, 'KV No.1 AMRITSAR CANTT');
INSERT INTO school (id, school_name) VALUES ( 816, 'KV No.1 ARAKKONAM');
INSERT INTO school (id, school_name) VALUES ( 817, 'KV No.1 ARMAPUR KANPUR');
INSERT INTO school (id, school_name) VALUES ( 818, 'KV No.1 BAJAJ NAGAR JAIPUR');
INSERT INTO school (id, school_name) VALUES ( 819, 'KV No.1 BANBASA CANTT');
INSERT INTO school (id, school_name) VALUES ( 820, 'KV No.1 BARAUNI');
INSERT INTO school (id, school_name) VALUES ( 821, 'KV No.1 BARODA');
INSERT INTO school (id, school_name) VALUES ( 822, 'KV No.1 BHOPAL');
INSERT INTO school (id, school_name) VALUES ( 823, 'KV No.1 BHUBANESHWAR');
INSERT INTO school (id, school_name) VALUES ( 824, 'KV No.1 BHUSAWAL');
INSERT INTO school (id, school_name) VALUES ( 825, 'KV No.1 BINNAGURI CANTT');
INSERT INTO school (id, school_name) VALUES ( 826, 'KV No.1 BOKARO DBS CITY');
INSERT INTO school (id, school_name) VALUES ( 827, 'KV No.1 BOLANGIR');
INSERT INTO school (id, school_name) VALUES ( 828, 'KV No.1 CALICUT');
INSERT INTO school (id, school_name) VALUES ( 829, 'KV No.1 CHAKERI KANPUR');
INSERT INTO school (id, school_name) VALUES ( 830, 'KV No.1 CHANDIMANDIR');
INSERT INTO school (id, school_name) VALUES ( 831, 'KV No.1 COLABA');
INSERT INTO school (id, school_name) VALUES ( 832, 'KV No.1 DEHUROAD');
INSERT INTO school (id, school_name) VALUES ( 833, 'KV No.1 DEVLALI');
INSERT INTO school (id, school_name) VALUES ( 834, 'KV No.1 FARidABAD');
INSERT INTO school (id, school_name) VALUES ( 835, 'KV No.1 GANDHI NAGAR (JAMMU)');
INSERT INTO school (id, school_name) VALUES ( 836, 'KV No.1 GANDHINAGAR');
INSERT INTO school (id, school_name) VALUES ( 837, 'KV No.1 GAYA');
INSERT INTO school (id, school_name) VALUES ( 838, 'KV No.1 GOLCONDA');
INSERT INTO school (id, school_name) VALUES ( 839, 'KV No.1 GORAKHPUR');
INSERT INTO school (id, school_name) VALUES ( 840, 'KV No.1 GWALIOR');
INSERT INTO school (id, school_name) VALUES ( 841, 'KV No.1 HINDON');
INSERT INTO school (id, school_name) VALUES ( 842, 'KV No.1 HUBLI');
INSERT INTO school (id, school_name) VALUES ( 843, 'KV No.1 INDORE');
INSERT INTO school (id, school_name) VALUES ( 844, 'KV No.1 ISHAPORE');
INSERT INTO school (id, school_name) VALUES ( 845, 'KV No.1 ITANAGAR');
INSERT INTO school (id, school_name) VALUES ( 846, 'KV No.1 ITARASI');
INSERT INTO school (id, school_name) VALUES ( 847, 'KV No.1 JALANDHAR CANTT.');
INSERT INTO school (id, school_name) VALUES ( 848, 'KV No.1 JHANSI CANTT');
INSERT INTO school (id, school_name) VALUES ( 849, 'KV No.1 JIPMER CAMPUS PONDICHERRY');
INSERT INTO school (id, school_name) VALUES ( 850, 'KV No.1 KALAIKUNDA');
INSERT INTO school (id, school_name) VALUES ( 851, 'KV No.1 KALPAKKAM');
INSERT INTO school (id, school_name) VALUES ( 852, 'KV No.1 KANCHRAPARA');
INSERT INTO school (id, school_name) VALUES ( 853, 'KV No.1 KANKARBAGH PATNA');
INSERT INTO school (id, school_name) VALUES ( 854, 'KV No.1 KATNI');
INSERT INTO school (id, school_name) VALUES ( 855, 'KV No.1 KOTA');
INSERT INTO school (id, school_name) VALUES ( 856, 'KV No.1 M.R. CAMPUS AHMEDABAD');
INSERT INTO school (id, school_name) VALUES ( 857, 'KV No.1 MADURAI');
INSERT INTO school (id, school_name) VALUES ( 858, 'KV No.1 MANGALORE');
INSERT INTO school (id, school_name) VALUES ( 859, 'KV No.1 MORADABAD');
INSERT INTO school (id, school_name) VALUES ( 860, 'KV No.1 NASIK ROAD CAMP');
INSERT INTO school (id, school_name) VALUES ( 861, 'KV No.1 NAUSENA BAGH');
INSERT INTO school (id, school_name) VALUES ( 862, 'KV No.1 PATIALA');
INSERT INTO school (id, school_name) VALUES ( 863, 'KV No.1 PORT BLAIR');
INSERT INTO school (id, school_name) VALUES ( 864, 'KV No.1 RAIPUR');
INSERT INTO school (id, school_name) VALUES ( 865, 'KV No.1 RCF HUSSAINPUR');
INSERT INTO school (id, school_name) VALUES ( 866, 'KV No.1 REWA');
INSERT INTO school (id, school_name) VALUES ( 867, 'KV No.1 ROORKEE');
INSERT INTO school (id, school_name) VALUES ( 868, 'KV No.1 SAGAR CANTT');
INSERT INTO school (id, school_name) VALUES ( 869, 'KV No.1 SALT LAKE');
INSERT INTO school (id, school_name) VALUES ( 870, 'KV No.1 SAMBALPUR');
INSERT INTO school (id, school_name) VALUES ( 871, 'KV No.1 SATNA');
INSERT INTO school (id, school_name) VALUES ( 872, 'KV No.1 SHAHJAHANPUR CANTT');
INSERT INTO school (id, school_name) VALUES ( 873, 'KV No.1 SIBSAGAR');
INSERT INTO school (id, school_name) VALUES ( 874, 'KV No.1 SRINAGAR');
INSERT INTO school (id, school_name) VALUES ( 875, 'KV No.1 SRIVIJAYA NAGAR');
INSERT INTO school (id, school_name) VALUES ( 876, 'KV No.1 SURAT');
INSERT INTO school (id, school_name) VALUES ( 877, 'KV No.1 TEZPUR');
INSERT INTO school (id, school_name) VALUES ( 878, 'KV No.1 THIMAYYA MARG BHATINDA');
INSERT INTO school (id, school_name) VALUES ( 879, 'KV No.1 TIRUCHIRAPALLI');
INSERT INTO school (id, school_name) VALUES ( 880, 'KV No.1 TIRUPATI');
INSERT INTO school (id, school_name) VALUES ( 881, 'KV No.1 UDHAMPUR');
INSERT INTO school (id, school_name) VALUES ( 882, 'KV No.1 VASCO-DA-GAMA');
INSERT INTO school (id, school_name) VALUES ( 883, 'KV No.1 VIJAYAWADA');
INSERT INTO school (id, school_name) VALUES ( 884, 'KV No.2 (NTPC) KORBA');
INSERT INTO school (id, school_name) VALUES ( 885, 'KV No.2 ADAMPUR');
INSERT INTO school (id, school_name) VALUES ( 886, 'KV No.2 AGRA CANTT');
INSERT INTO school (id, school_name) VALUES ( 887, 'KV No.2 AKHNOOR');
INSERT INTO school (id, school_name) VALUES ( 888, 'KV No.2 AMBALA CANTT.');
INSERT INTO school (id, school_name) VALUES ( 889, 'KV No.2 ANGUL');
INSERT INTO school (id, school_name) VALUES ( 890, 'KV No.2 ARMAPUR KANPUR');
INSERT INTO school (id, school_name) VALUES ( 891, 'KV No.2 ARMY PATHANKOT');
INSERT INTO school (id, school_name) VALUES ( 892, 'KV No.2 BAILEY ROAD PATNA');
INSERT INTO school (id, school_name) VALUES ( 893, 'KV No.2 BALASORE');
INSERT INTO school (id, school_name) VALUES ( 894, 'KV No.2 BARODA');
INSERT INTO school (id, school_name) VALUES ( 895, 'KV No.2 BELGAUM CANTT');
INSERT INTO school (id, school_name) VALUES ( 896, 'KV No.2 Bhopal');
INSERT INTO school (id, school_name) VALUES ( 897, 'KV No.2 BHUJ CANTT.');
INSERT INTO school (id, school_name) VALUES ( 898, 'KV No.2 BIKANER');
INSERT INTO school (id, school_name) VALUES ( 899, 'KV No.2 BINNAGURI');
INSERT INTO school (id, school_name) VALUES ( 900, 'KV No.2 BOLANGIR');
INSERT INTO school (id, school_name) VALUES ( 901, 'KV No.2 CALICUT');
INSERT INTO school (id, school_name) VALUES ( 902, 'KV No.2 CHAKERI');
INSERT INTO school (id, school_name) VALUES ( 903, 'KV No.2 CHAMERA');
INSERT INTO school (id, school_name) VALUES ( 904, 'KV No.2 CHANDIMANDIR');
INSERT INTO school (id, school_name) VALUES ( 905, 'KV No.2 CHHINDWARA');
INSERT INTO school (id, school_name) VALUES ( 906, 'KV No.2 COCHIN');
INSERT INTO school (id, school_name) VALUES ( 907, 'KV No.2 COLABA');
INSERT INTO school (id, school_name) VALUES ( 908, 'KV No.2 CUTTACK');
INSERT INTO school (id, school_name) VALUES ( 909, 'KV No.2 DARBHANGA');
INSERT INTO school (id, school_name) VALUES ( 910, 'KV No.2 DEHUROAD');
INSERT INTO school (id, school_name) VALUES ( 911, 'KV No.2 DELHI CANTT');
INSERT INTO school (id, school_name) VALUES ( 912, 'KV No.2 DHANBAD');
INSERT INTO school (id, school_name) VALUES ( 913, 'KV No.2 DUNDIGAL');
INSERT INTO school (id, school_name) VALUES ( 914, 'KV No.2 EKLINGGARH UDAIPUR');
INSERT INTO school (id, school_name) VALUES ( 915, 'KV No.2 FARidABAD');
INSERT INTO school (id, school_name) VALUES ( 916, 'KV No.2 FEROZEPUR CANTT.');
INSERT INTO school (id, school_name) VALUES ( 917, 'KV No.2 GAYA');
INSERT INTO school (id, school_name) VALUES ( 918, 'KV No.2 GOLCONDA');
INSERT INTO school (id, school_name) VALUES ( 919, 'KV No.2 GORAKHPUR');
INSERT INTO school (id, school_name) VALUES ( 920, 'KV No.2 HAPP TRICHY-25');
INSERT INTO school (id, school_name) VALUES ( 921, 'KV No.2 HINDON');
INSERT INTO school (id, school_name) VALUES ( 922, 'KV No.2 HUBLI');
INSERT INTO school (id, school_name) VALUES ( 923, 'KV No.2 ISHAPORE');
INSERT INTO school (id, school_name) VALUES ( 924, 'KV No.2 ITANAGAR');
INSERT INTO school (id, school_name) VALUES ( 925, 'KV No.2 ITARASI');
INSERT INTO school (id, school_name) VALUES ( 926, 'KV No.2 JAIPUR CANTT');
INSERT INTO school (id, school_name) VALUES ( 927, 'KV No.2 JALANDHAR CANTT.');
INSERT INTO school (id, school_name) VALUES ( 928, 'KV No.2 JAMMU CANTT');
INSERT INTO school (id, school_name) VALUES ( 929, 'KV No.2 JAMNAGAR');
INSERT INTO school (id, school_name) VALUES ( 930, 'KV No.2 JHANSI CANTT');
INSERT INTO school (id, school_name) VALUES ( 931, 'KV No.2 KALAIKUNDA');
INSERT INTO school (id, school_name) VALUES ( 932, 'KV No.2 KALAPET PONDICHERRY');
INSERT INTO school (id, school_name) VALUES ( 933, 'KV No.2 KALPAKKAM');
INSERT INTO school (id, school_name) VALUES ( 934, 'KV No.2 KANCHRAPARA');
INSERT INTO school (id, school_name) VALUES ( 935, 'KV No.2 KASRAGOD');
INSERT INTO school (id, school_name) VALUES ( 936, 'KV No.2 KOTA');
INSERT INTO school (id, school_name) VALUES ( 937, 'KV No.2 MADURAI');
INSERT INTO school (id, school_name) VALUES ( 938, 'KV No.2 MANGALURU');
INSERT INTO school (id, school_name) VALUES ( 939, 'KV No.2 NAUSENA BAGH');
INSERT INTO school (id, school_name) VALUES ( 940, 'KV No.2 NEEMUCH');
INSERT INTO school (id, school_name) VALUES ( 941, 'KV No.2 PORT BLAIR');
INSERT INTO school (id, school_name) VALUES ( 942, 'KV No.2 RAIPUR');
INSERT INTO school (id, school_name) VALUES ( 943, 'KV No.2 REWA');
INSERT INTO school (id, school_name) VALUES ( 944, 'KV No.2 ROORKEE');
INSERT INTO school (id, school_name) VALUES ( 945, 'KV No.2 SAGAR');
INSERT INTO school (id, school_name) VALUES ( 946, 'KV No.2 SALT LAKE');
INSERT INTO school (id, school_name) VALUES ( 947, 'KV No.2 SAMBALPUR');
INSERT INTO school (id, school_name) VALUES ( 948, 'KV No.2 SATNA');
INSERT INTO school (id, school_name) VALUES ( 949, 'KV No.2 SIBSAGAR');
INSERT INTO school (id, school_name) VALUES ( 950, 'KV No.2 SIRSA');
INSERT INTO school (id, school_name) VALUES ( 951, 'KV No.2 SRIVIJAYA NAGAR');
INSERT INTO school (id, school_name) VALUES ( 952, 'KV No.2 SURATGARH CANTT');
INSERT INTO school (id, school_name) VALUES ( 953, 'KV No.2 TAMBARAM');
INSERT INTO school (id, school_name) VALUES ( 954, 'KV No.2 TIRUPATI');
INSERT INTO school (id, school_name) VALUES ( 955, 'KV No.2 UDHAMPUR');
INSERT INTO school (id, school_name) VALUES ( 956, 'KV No.2 VASCO-DA-GAMA');
INSERT INTO school (id, school_name) VALUES ( 957, 'KV No.2 VIJAYAWADA');
INSERT INTO school (id, school_name) VALUES ( 958, 'KV No.3 (AF) JAMNAGAR');
INSERT INTO school (id, school_name) VALUES ( 959, 'KV No.3 (AFS) BARODA');
INSERT INTO school (id, school_name) VALUES ( 960, 'KV No.3 AGRA CANTT');
INSERT INTO school (id, school_name) VALUES ( 961, 'KV No.3 AMBALA CANTT.');
INSERT INTO school (id, school_name) VALUES ( 962, 'KV No.3 AMRITSAR NEW CANTT');
INSERT INTO school (id, school_name) VALUES ( 963, 'KV No.3 BELGAUM');
INSERT INTO school (id, school_name) VALUES ( 964, 'KV No.3 Bhopal');
INSERT INTO school (id, school_name) VALUES ( 965, 'KV No.3 CHAKERI');
INSERT INTO school (id, school_name) VALUES ( 966, 'KV No.3 COCHIN');
INSERT INTO school (id, school_name) VALUES ( 967, 'KV No.3 COLABA');
INSERT INTO school (id, school_name) VALUES ( 968, 'KV No.3 DELHI CANTT');
INSERT INTO school (id, school_name) VALUES ( 969, 'KV No.3 FARidABAD');
INSERT INTO school (id, school_name) VALUES ( 970, 'KV No.3 JALANDHAR CANTT.');
INSERT INTO school (id, school_name) VALUES ( 971, 'KV No.3 JHANSI CANTT');
INSERT INTO school (id, school_name) VALUES ( 972, 'KV No.3 JORHAT');
INSERT INTO school (id, school_name) VALUES ( 973, 'KV No.3 MANCHESWAR');
INSERT INTO school (id, school_name) VALUES ( 974, 'KV No.3 MORAR CANTT');
INSERT INTO school (id, school_name) VALUES ( 975, 'KV No.3 MREC JAIPUR');
INSERT INTO school (id, school_name) VALUES ( 976, 'KV No.3 PATHANKOT');
INSERT INTO school (id, school_name) VALUES ( 977, 'KV No.3 PATIALA');
INSERT INTO school (id, school_name) VALUES ( 978, 'KV No.3 SAGAR');
INSERT INTO school (id, school_name) VALUES ( 979, 'KV No.4 (AFS) Gwalior');
INSERT INTO school (id, school_name) VALUES ( 980, 'KV No.4 (AFS) JALANDHAR CANTT.');
INSERT INTO school (id, school_name) VALUES ( 981, 'KV No.4 (KHATIPURA) JAIPUR');
INSERT INTO school (id, school_name) VALUES ( 982, 'KV No.4 AMBALA CANTT.');
INSERT INTO school (id, school_name) VALUES ( 983, 'KV No.4 BARODA');
INSERT INTO school (id, school_name) VALUES ( 984, 'KV No.4 BHATINDA');
INSERT INTO school (id, school_name) VALUES ( 985, 'KV No.4 BHUBANESHWAR');
INSERT INTO school (id, school_name) VALUES ( 986, 'KV No.4 DELHI CANTT KANDHAR LINES');
INSERT INTO school (id, school_name) VALUES ( 987, 'KV No.4 MAMOON CANTT PATHANKOT');
INSERT INTO school (id, school_name) VALUES ( 988, 'KV No.4 VARANASI');
INSERT INTO school (id, school_name) VALUES ( 989, 'KV No.5 BHATINDA');
INSERT INTO school (id, school_name) VALUES ( 990, 'KV No.5 KALINGA NAGAR');
INSERT INTO school (id, school_name) VALUES ( 991, 'KV No.5 MANSAROVER JAIPUR');
INSERT INTO school (id, school_name) VALUES ( 992, 'KV No.6 POKHARIPUT');
INSERT INTO school (id, school_name) VALUES ( 993, 'KV No.6 SECTOR III PRATAP NAGAR');
INSERT INTO school (id, school_name) VALUES ( 994, 'KV NOidA');
INSERT INTO school (id, school_name) VALUES ( 995, 'KV NTPC BADARPUR');
INSERT INTO school (id, school_name) VALUES ( 996, 'KV NTPC DADRI');
INSERT INTO school (id, school_name) VALUES ( 997, 'KV NTPC KANIHA');
INSERT INTO school (id, school_name) VALUES ( 998, 'KV NTPC KAYAMKULAM');
INSERT INTO school (id, school_name) VALUES ( 999, 'KV NTPC SHAKTINAGAR');
INSERT INTO school (id, school_name) VALUES ( 1000, 'KV NUAPADA');
INSERT INTO school (id, school_name) VALUES ( 1001, 'KV NUBRA');
INSERT INTO school (id, school_name) VALUES ( 1002, 'KV OCF AVADI');
INSERT INTO school (id, school_name) VALUES ( 1003, 'KV OCF CHANDIGARH');
INSERT INTO school (id, school_name) VALUES ( 1004, 'KV OEF DEHRADUN RAIPUR');
INSERT INTO school (id, school_name) VALUES ( 1005, 'KV OEF HAZARATPUR');
INSERT INTO school (id, school_name) VALUES ( 1006, 'KV OEF Taigoar Road KANPUR');
INSERT INTO school (id, school_name) VALUES ( 1007, 'KV OKHA');
INSERT INTO school (id, school_name) VALUES ( 1008, 'KV OLD CANTT ALLAHABAD');
INSERT INTO school (id, school_name) VALUES ( 1009, 'KV ONGC ANKLESHWAR');
INSERT INTO school (id, school_name) VALUES ( 1010, 'KV ONGC CAMBEY');
INSERT INTO school (id, school_name) VALUES ( 1011, 'KV ONGC CHANDKHEDA');
INSERT INTO school (id, school_name) VALUES ( 1012, 'KV ONGC DEHRADUN');
INSERT INTO school (id, school_name) VALUES ( 1013, 'KV ONGC MEHSANA');
INSERT INTO school (id, school_name) VALUES ( 1014, 'KV ONGC No.2 JORHAT');
INSERT INTO school (id, school_name) VALUES ( 1015, 'KV ONGC No.3 SURAT');
INSERT INTO school (id, school_name) VALUES ( 1016, 'KV ONGOLE');
INSERT INTO school (id, school_name) VALUES ( 1017, 'KV PACHMARHI');
INSERT INTO school (id, school_name) VALUES ( 1018, 'KV PAHALGAON');
INSERT INTO school (id, school_name) VALUES ( 1019, 'KV PAINAVU');
INSERT INTO school (id, school_name) VALUES ( 1020, 'KV PALAMPUR');
INSERT INTO school (id, school_name) VALUES ( 1021, 'KV PALI');
INSERT INTO school (id, school_name) VALUES ( 1022, 'KV PALLA PURAM OTTAPALAM');
INSERT INTO school (id, school_name) VALUES ( 1023, 'KV PALUWAS');
INSERT INTO school (id, school_name) VALUES ( 1024, 'KV PALWAL');
INSERT INTO school (id, school_name) VALUES ( 1025, 'KV PANAGARH');
INSERT INTO school (id, school_name) VALUES ( 1026, 'KV PANDHURNA');
INSERT INTO school (id, school_name) VALUES ( 1027, 'KV PANNA');
INSERT INTO school (id, school_name) VALUES ( 1028, 'KV PAPANKALAN (SPG) DWARKA');
INSERT INTO school (id, school_name) VALUES ( 1029, 'KV PARADIP PORT');
INSERT INTO school (id, school_name) VALUES ( 1030, 'KV PARBHANI');
INSERT INTO school (id, school_name) VALUES ( 1031, 'KV PASCHIM VIHAR');
INSERT INTO school (id, school_name) VALUES ( 1032, 'KV PASSIGAHT');
INSERT INTO school (id, school_name) VALUES ( 1033, 'KV PATAN');
INSERT INTO school (id, school_name) VALUES ( 1034, 'KV PATRATU');
INSERT INTO school (id, school_name) VALUES ( 1035, 'KV PAURI');
INSERT INTO school (id, school_name) VALUES ( 1036, 'KV PAYYANUR');
INSERT INTO school (id, school_name) VALUES ( 1037, 'KV PERAMBALUR');
INSERT INTO school (id, school_name) VALUES ( 1038, 'KV PHULERA');
INSERT INTO school (id, school_name) VALUES ( 1039, 'KV PICKET SECUNDERABAD');
INSERT INTO school (id, school_name) VALUES ( 1040, 'KV PILIBHIT');
INSERT INTO school (id, school_name) VALUES ( 1041, 'KV PITAMPURA');
INSERT INTO school (id, school_name) VALUES ( 1042, 'KV PITHORAGARH');
INSERT INTO school (id, school_name) VALUES ( 1043, 'KV PL MEERUT CANTT');
INSERT INTO school (id, school_name) VALUES ( 1044, 'KV PONDA');
INSERT INTO school (id, school_name) VALUES ( 1045, 'KV PORBANDER');
INSERT INTO school (id, school_name) VALUES ( 1046, 'KV PRAGATIVIHAR');
INSERT INTO school (id, school_name) VALUES ( 1047, 'KV PULGAON CAMP');
INSERT INTO school (id, school_name) VALUES ( 1048, 'KV PURI');
INSERT INTO school (id, school_name) VALUES ( 1049, 'KV PURNIA');
INSERT INTO school (id, school_name) VALUES ( 1050, 'KV PUSA-RAU');
INSERT INTO school (id, school_name) VALUES ( 1051, 'KV PUSHP VIHAR SAKET');
INSERT INTO school (id, school_name) VALUES ( 1052, 'KV RAE BARELI');
INSERT INTO school (id, school_name) VALUES ( 1053, 'KV RAGHUNATHPURA (NARNAUL)');
INSERT INTO school (id, school_name) VALUES ( 1054, 'KV RAICHUR');
INSERT INTO school (id, school_name) VALUES ( 1055, 'KV RAIGARH');
INSERT INTO school (id, school_name) VALUES ( 1056, 'KV RAILWAY COLONY KHARAGPUR');
INSERT INTO school (id, school_name) VALUES ( 1057, 'KV RAILWAY idGAH AGRA');
INSERT INTO school (id, school_name) VALUES ( 1058, 'KV RAISEN');
INSERT INTO school (id, school_name) VALUES ( 1059, 'KV RAIWALA');
INSERT INTO school (id, school_name) VALUES ( 1060, 'KV RAJAMPALLI');
INSERT INTO school (id, school_name) VALUES ( 1061, 'KV RAJAMPET');
INSERT INTO school (id, school_name) VALUES ( 1062, 'KV RAJGARHI');
INSERT INTO school (id, school_name) VALUES ( 1063, 'KV RAJGARHI');
INSERT INTO school (id, school_name) VALUES ( 1064, 'KV RAJKOT');
INSERT INTO school (id, school_name) VALUES ( 1065, 'KV RAJNANDGAON');
INSERT INTO school (id, school_name) VALUES ( 1066, 'KV RAMBI (TEESTA LOW DAM PROJECT-III)');
INSERT INTO school (id, school_name) VALUES ( 1067, 'KV RAMESWARAM');
INSERT INTO school (id, school_name) VALUES ( 1068, 'KV RAMGARH CANTT');
INSERT INTO school (id, school_name) VALUES ( 1069, 'KV RANCHI HINOO');
INSERT INTO school (id, school_name) VALUES ( 1070, 'KV RANCHI NAMKUM');
INSERT INTO school (id, school_name) VALUES ( 1071, 'KV RANGAPAHAR CANTT');
INSERT INTO school (id, school_name) VALUES ( 1072, 'KV RANGAPARA NF RAILWAY');
INSERT INTO school (id, school_name) VALUES ( 1073, 'KV RANGE HILLS ESTATE');
INSERT INTO school (id, school_name) VALUES ( 1074, 'KV RANGIYA N.F. RAILWAY');
INSERT INTO school (id, school_name) VALUES ( 1075, 'KV RANGPURI');
INSERT INTO school (id, school_name) VALUES ( 1076, 'KV RANIKHET');
INSERT INTO school (id, school_name) VALUES ( 1077, 'KV RATLAM');
INSERT INTO school (id, school_name) VALUES ( 1078, 'KV RAYAGADA');
INSERT INTO school (id, school_name) VALUES ( 1079, 'KV RBNM SALBONI');
INSERT INTO school (id, school_name) VALUES ( 1080, 'KV RCF KAPURTHALA HUSSAINPUR II');
INSERT INTO school (id, school_name) VALUES ( 1081, 'KV RDSO LUCKNOW');
INSERT INTO school (id, school_name) VALUES ( 1082, 'KV RECONG PEO');
INSERT INTO school (id, school_name) VALUES ( 1083, 'KV REONA UCHA');
INSERT INTO school (id, school_name) VALUES ( 1084, 'KV REWARI');
INSERT INTO school (id, school_name) VALUES ( 1085, 'KV RISHIKESH');
INSERT INTO school (id, school_name) VALUES ( 1086, 'KV RLY. COLONY GANDHidHAM');
INSERT INTO school (id, school_name) VALUES ( 1087, 'KV ROHTAK');
INSERT INTO school (id, school_name) VALUES ( 1088, 'KV ROING');
INSERT INTO school (id, school_name) VALUES ( 1089, 'KV ROURKELA');
INSERT INTO school (id, school_name) VALUES ( 1090, 'KV RUBBER BOARD KOTTAYAM');
INSERT INTO school (id, school_name) VALUES ( 1091, 'KV SABARMATI');
INSERT INTO school (id, school_name) VALUES ( 1092, 'KV SAC AHMEDABAD');
INSERT INTO school (id, school_name) VALUES ( 1093, 'KV SAGAR No.4 (HSGV)');
INSERT INTO school (id, school_name) VALUES ( 1094, 'KV SAHARSA');
INSERT INTO school (id, school_name) VALUES ( 1095, 'KV SAINIK VIHAR');
INSERT INTO school (id, school_name) VALUES ( 1096, 'KV SAINJ');
INSERT INTO school (id, school_name) VALUES ( 1097, 'KV SAMALKHA BEHOLI');
INSERT INTO school (id, school_name) VALUES ( 1098, 'KV SAMASTIPUR');
INSERT INTO school (id, school_name) VALUES ( 1099, 'KV SAMBA');
INSERT INTO school (id, school_name) VALUES ( 1100, 'KV SANDHOL');
INSERT INTO school (id, school_name) VALUES ( 1101, 'KV SANTRAGACHI');
INSERT INTO school (id, school_name) VALUES ( 1102, 'KV SAP THIRUVANANTHAPURAM');
INSERT INTO school (id, school_name) VALUES ( 1103, 'KV SARAIKELA KHARSAWAN');
INSERT INTO school (id, school_name) VALUES ( 1104, 'KV SARAIPALLI');
INSERT INTO school (id, school_name) VALUES ( 1105, 'KV SASARAM');
INSERT INTO school (id, school_name) VALUES ( 1106, 'KV SATTENAPALLI');
INSERT INTO school (id, school_name) VALUES ( 1107, 'KV SAWAI MADHOPUR');
INSERT INTO school (id, school_name) VALUES ( 1108, 'KV SCR NANDED');
INSERT INTO school (id, school_name) VALUES ( 1109, 'KV SECTOR 12 DWARKA');
INSERT INTO school (id, school_name) VALUES ( 1110, 'KV SECTOR 22 ROHINI');
INSERT INTO school (id, school_name) VALUES ( 1111, 'KV SECTOR 25 ROHINI');
INSERT INTO school (id, school_name) VALUES ( 1112, 'KV SECTOR 28 ROHINI');
INSERT INTO school (id, school_name) VALUES ( 1113, 'KV SECTOR 31 CHANDIGARH');
INSERT INTO school (id, school_name) VALUES ( 1114, 'KV SECTOR 47 CHANDIGARH');
INSERT INTO school (id, school_name) VALUES ( 1115, 'KV SECTOR 5 DWARKA');
INSERT INTO school (id, school_name) VALUES ( 1116, 'KV SECTOR II R.K. PURAM');
INSERT INTO school (id, school_name) VALUES ( 1117, 'KV SECTOR III ROHINI');
INSERT INTO school (id, school_name) VALUES ( 1118, 'KV SECTOR IV R.K. PURAM');
INSERT INTO school (id, school_name) VALUES ( 1119, 'KV SECTOR VIII R.K. PURAM');
INSERT INTO school (id, school_name) VALUES ( 1120, 'KV SECTOR VIII ROHINI');
INSERT INTO school (id, school_name) VALUES ( 1121, 'KV SECUNDERABAD. BOLARUM');
INSERT INTO school (id, school_name) VALUES ( 1122, 'KV SECUNDERABAD. BOWENPALLY');
INSERT INTO school (id, school_name) VALUES ( 1123, 'KV SEHORE');
INSERT INTO school (id, school_name) VALUES ( 1124, 'KV SEONI');
INSERT INTO school (id, school_name) VALUES ( 1125, 'KV SEONI MALWA');
INSERT INTO school (id, school_name) VALUES ( 1126, 'KV SEVOKE ROAD');
INSERT INTO school (id, school_name) VALUES ( 1127, 'KV SGPGI LUCKNOW');
INSERT INTO school (id, school_name) VALUES ( 1128, 'KV SHAHADARA');
INSERT INTO school (id, school_name) VALUES ( 1129, 'KV SHAHADOL');
INSERT INTO school (id, school_name) VALUES ( 1130, 'KV SHAHIBGANJ');
INSERT INTO school (id, school_name) VALUES ( 1131, 'KV SHAJAPUR');
INSERT INTO school (id, school_name) VALUES ( 1132, 'KV SHAKURBASTI');
INSERT INTO school (id, school_name) VALUES ( 1133, 'KV SHALIMAR BAGH');
INSERT INTO school (id, school_name) VALUES ( 1134, 'KV SHAMGARH');
INSERT INTO school (id, school_name) VALUES ( 1135, 'KV SHEOHAR');
INSERT INTO school (id, school_name) VALUES ( 1136, 'KV SHEOPUR');
INSERT INTO school (id, school_name) VALUES ( 1137, 'KV SHIMLA');
INSERT INTO school (id, school_name) VALUES ( 1138, 'KV SHIVAMOGGA');
INSERT INTO school (id, school_name) VALUES ( 1139, 'KV SHIVGARH RAEBARELI');
INSERT INTO school (id, school_name) VALUES ( 1140, 'KV SHOLAPUR');
INSERT INTO school (id, school_name) VALUES ( 1141, 'KV SHRAWASTI');
INSERT INTO school (id, school_name) VALUES ( 1142, 'KV SHRI GANGA NAGAR CANTT');
INSERT INTO school (id, school_name) VALUES ( 1143, 'KV SidDIPET');
INSERT INTO school (id, school_name) VALUES ( 1144, 'KV SidHARTH NAGAR');
INSERT INTO school (id, school_name) VALUES ( 1145, 'KV SidHI');
INSERT INTO school (id, school_name) VALUES ( 1146, 'KV SIKAR');
INSERT INTO school (id, school_name) VALUES ( 1147, 'KV SILCHAR');
INSERT INTO school (id, school_name) VALUES ( 1148, 'KV Silvassa');
INSERT INTO school (id, school_name) VALUES ( 1149, 'KV SIMDEGA');
INSERT INTO school (id, school_name) VALUES ( 1150, 'KV SINGRAULI');
INSERT INTO school (id, school_name) VALUES ( 1151, 'KV SIRCILLA');
INSERT INTO school (id, school_name) VALUES ( 1152, 'KV SITAPUR');
INSERT INTO school (id, school_name) VALUES ( 1153, 'KV SIVAGANGA');
INSERT INTO school (id, school_name) VALUES ( 1154, 'KV SIWAN');
INSERT INTO school (id, school_name) VALUES ( 1155, 'KV SL MEERUT CANTT');
INSERT INTO school (id, school_name) VALUES ( 1156, 'KV SLIET LONGOWAL');
INSERT INTO school (id, school_name) VALUES ( 1157, 'KV SOHNA ROAD No.2 GURGAON');
INSERT INTO school (id, school_name) VALUES ( 1158, 'KV SONEPUR');
INSERT INTO school (id, school_name) VALUES ( 1159, 'KV SONPUR');
INSERT INTO school (id, school_name) VALUES ( 1160, 'KV SOURKHAND. TEHRI');
INSERT INTO school (id, school_name) VALUES ( 1161, 'KV SRIKAKULAM');
INSERT INTO school (id, school_name) VALUES ( 1162, 'KV SSB CAMPUS GADANIA PALIA KALAN');
INSERT INTO school (id, school_name) VALUES ( 1163, 'KV SSB GWALDHAM');
INSERT INTO school (id, school_name) VALUES ( 1164, 'KV STEEL PROJECT');
INSERT INTO school (id, school_name) VALUES ( 1165, 'KV STPS SURATGARH');
INSERT INTO school (id, school_name) VALUES ( 1166, 'KV SUBATHU');
INSERT INTO school (id, school_name) VALUES ( 1167, 'KV SUKMA');
INSERT INTO school (id, school_name) VALUES ( 1168, 'KV SULUR');
INSERT INTO school (id, school_name) VALUES ( 1169, 'KV SUNABEDA');
INSERT INTO school (id, school_name) VALUES ( 1170, 'KV SUNDARGARH');
INSERT INTO school (id, school_name) VALUES ( 1171, 'KV SURAJPUR');
INSERT INTO school (id, school_name) VALUES ( 1172, 'KV SURANASSI');
INSERT INTO school (id, school_name) VALUES ( 1173, 'KV SURDA GHATSILA');
INSERT INTO school (id, school_name) VALUES ( 1174, 'KV TAGORE GARDEN');
INSERT INTO school (id, school_name) VALUES ( 1175, 'KV TALBEHAT');
INSERT INTO school (id, school_name) VALUES ( 1176, 'KV TAMENGLONG');
INSERT INTO school (id, school_name) VALUES ( 1177, 'KV TAMULPUR');
INSERT INTO school (id, school_name) VALUES ( 1178, 'KV TARKESWAR');
INSERT INTO school (id, school_name) VALUES ( 1179, 'KV TATA NAGAR');
INSERT INTO school (id, school_name) VALUES ( 1180, 'KV TAWANG');
INSERT INTO school (id, school_name) VALUES ( 1181, 'KV TEHRAN');
INSERT INTO school (id, school_name) VALUES ( 1182, 'KV TENALI');
INSERT INTO school (id, school_name) VALUES ( 1183, 'KV TENGA VALLEY');
INSERT INTO school (id, school_name) VALUES ( 1184, 'KV TEZPUR UNIVERSITY');
INSERT INTO school (id, school_name) VALUES ( 1185, 'KV TEZU');
INSERT INTO school (id, school_name) VALUES ( 1186, 'KV TFRI JABALPUR');
INSERT INTO school (id, school_name) VALUES ( 1187, 'KV THALESSERY');
INSERT INTO school (id, school_name) VALUES ( 1188, 'KV THIRUVANNAMALAI');
INSERT INTO school (id, school_name) VALUES ( 1189, 'KV TIBRI CANTT');
INSERT INTO school (id, school_name) VALUES ( 1190, 'KV TIKAMGARH');
INSERT INTO school (id, school_name) VALUES ( 1191, 'KV TINSUKIA');
INSERT INTO school (id, school_name) VALUES ( 1192, 'KV TINVARI');
INSERT INTO school (id, school_name) VALUES ( 1193, 'KV TIRUCHUR');
INSERT INTO school (id, school_name) VALUES ( 1194, 'KV TONK');
INSERT INTO school (id, school_name) VALUES ( 1195, 'KV TRIMULGHERY SECUNDERABAD');
INSERT INTO school (id, school_name) VALUES ( 1196, 'KV TRIVENDRAM PANGODE');
INSERT INTO school (id, school_name) VALUES ( 1197, 'KV TRIVENDRAM PATTOM');
INSERT INTO school (id, school_name) VALUES ( 1198, 'KV TULI');
INSERT INTO school (id, school_name) VALUES ( 1199, 'KV TUMKUR');
INSERT INTO school (id, school_name) VALUES ( 1200, 'KV TURA');
INSERT INTO school (id, school_name) VALUES ( 1201, 'KV TUTING');
INSERT INTO school (id, school_name) VALUES ( 1202, 'KV UBHAWAL');
INSERT INTO school (id, school_name) VALUES ( 1203, 'KV UDALGURI');
INSERT INTO school (id, school_name) VALUES ( 1204, 'KV UDUMALPET');
INSERT INTO school (id, school_name) VALUES ( 1205, 'KV UDUPI');
INSERT INTO school (id, school_name) VALUES ( 1206, 'KV UJJAIN');
INSERT INTO school (id, school_name) VALUES ( 1207, 'KV UKHRUL');
INSERT INTO school (id, school_name) VALUES ( 1208, 'KV UMARIA');
INSERT INTO school (id, school_name) VALUES ( 1209, 'KV UMROI CANTT');
INSERT INTO school (id, school_name) VALUES ( 1210, 'KV UNNAO');
INSERT INTO school (id, school_name) VALUES ( 1211, 'KV UPPAL No.II(SOI)');
INSERT INTO school (id, school_name) VALUES ( 1212, 'KV URI');
INSERT INTO school (id, school_name) VALUES ( 1213, 'KV UTTARKASHI');
INSERT INTO school (id, school_name) VALUES ( 1214, 'KV UTTARLAI');
INSERT INTO school (id, school_name) VALUES ( 1215, 'KV V V NAGAR');
INSERT INTO school (id, school_name) VALUES ( 1216, 'KV VARANASI CANTT');
INSERT INTO school (id, school_name) VALUES ( 1217, 'KV VARANGAON');
INSERT INTO school (id, school_name) VALUES ( 1218, 'KV VASANT KUNJ');
INSERT INTO school (id, school_name) VALUES ( 1219, 'KV VENKATAGIRI');
INSERT INTO school (id, school_name) VALUES ( 1220, 'KV VidISHA');
INSERT INTO school (id, school_name) VALUES ( 1221, 'KV VIJAYAPURA');
INSERT INTO school (id, school_name) VALUES ( 1222, 'KV VIKASPURI');
INSERT INTO school (id, school_name) VALUES ( 1223, 'KV VIRAMGAON');
INSERT INTO school (id, school_name) VALUES ( 1224, 'KV VIRUDUNAGAR');
INSERT INTO school (id, school_name) VALUES ( 1225, 'KV VIZIANAGARAM');
INSERT INTO school (id, school_name) VALUES ( 1226, 'KV VYASNAGAR');
INSERT INTO school (id, school_name) VALUES ( 1227, 'KV W&amp;AP YELAHANKA');
INSERT INTO school (id, school_name) VALUES ( 1228, 'KV WALTAIR');
INSERT INTO school (id, school_name) VALUES ( 1229, 'KV WARANGAL');
INSERT INTO school (id, school_name) VALUES ( 1230, 'KV WASHIM');
INSERT INTO school (id, school_name) VALUES ( 1231, 'KV WCL BARKUHI CHANDAMETTA');
INSERT INTO school (id, school_name) VALUES ( 1232, 'KV WCL SARNI');
INSERT INTO school (id, school_name) VALUES ( 1233, 'KV WELLINGTON');
INSERT INTO school (id, school_name) VALUES ( 1234, 'KV YAWATMAL');
INSERT INTO school (id, school_name) VALUES ( 1235, 'KV YESHWANTHPUR RAILWAY');
INSERT INTO school (id, school_name) VALUES ( 1236, 'KV YOL CANTT');
INSERT INTO school (id, school_name) VALUES ( 1237, 'KV ZAKHMA');
INSERT INTO school (id, school_name) VALUES ( 1238, 'KV ZERO HAPOLI');
INSERT INTO school (id, school_name) VALUES ( 1239, 'KV ZIRAKPUR');

insert into user (id, user_name, password,image_url) values (0,'0', 'John Dummy','https://graph.facebook.com/v2.5/10158336366967902/picture');
insert into user (id, user_name, password,image_url) values (-1,'1', 'Jane Dummy','https://graph.facebook.com/v2.5/10158336366967902/picture');

insert into class_room (id, school_id, class_number,year) values (0,1,1,1990);

insert into user_class_room_mapping (id, user_name, class_room_id) values (0,'10158336366967902',0);
insert into user_class_room_mapping (id, user_name, class_room_id) values (-1,'0',0);

